### ISSUE TITLE
Crash on game login

### ISSUE THREAD

**Issue by HansYolo** [awgil/ffxiv_bossmod#10]
Hi, i like this plugin, but on the new ffxiv patch 6.1 and dalamud api change, i get a crash everytime i login into the game. i'm using version 0.33
![Unbenannt](https://user-images.githubusercontent.com/57645543/163669373-c86f8d39-d4bc-4dfa-9dd9-d6d2f163de1d.png)

**Comment by awgil** [comment]
Please find and attach dalamud.log file (it should be in C:\Users\username\AppData\Roaming\XIVLauncher directory) - it should contain details about the crash.

**Comment by HimitsuYami** [comment]
I'm having this issue as well, here's a copy of my [dalamud.log](https://github.com/awgil/ffxiv_bossmod/files/8501196/dalamud.log)

**Comment by HansYolo** [comment]
[dalamud.log](https://github.com/awgil/ffxiv_bossmod/files/8501202/dalamud.log)

**Comment by awgil** [comment]
Thanks, that's weird, I'm not at home today, will try to fix tomorrow.

**Comment by AbooseYou** [comment]
![YZXJn2D0QC](https://user-images.githubusercontent.com/5286813/163711676-4df6447b-5c0e-4989-8c30-401157d9ac89.png)

dont no if you need this but this is from my logs

**Comment by awgil** [comment]
Should be fixed now. I have no idea why it was broken, did clean rebuild and it seems to have fixed the problem for friend. Please check.

**Comment by awgil** [comment]
Please send dalamud.log file, it should contain crash details
