### ISSUE TITLE
Sophia Unreal Eye mechanic locking camera movement when AI is enabled

### ISSUE THREAD

**Issue by Dedoooo** [awgil/ffxiv_bossmod#100]
When the mechanic starts it does it correctly however after that it locks the camera from moving even after the enemy is dead.
 it happened 100% of the time for 4 consecutive pulls.
if AI is disabled while the camera is locked because of the Eye mechanic it returns to normal and reenabling is good to use after without any issues.
 
 are knockbacks mechanics meant to be manually resolved or can AI do them too? wondering if its capable but I assume not at the moment.
 
 Everything else is excellent!! this plugin always amazes me.
 Thank you!

**Comment by awgil** [comment]
Rofl I'm surprised AI is even remotely working on things like Sophia.

I used it when multiboxing early ARR content, modules typically had to provide customized AI hints to make it work - and this is not done for e.g. EW modules.

Someday maybe AI will work in general case, but I don't expect it to happen soon :)
