### ISSUE TITLE
List of Trials?

### ISSUE THREAD

**Issue by RedLightBandit** [awgil/ffxiv_bossmod#101]
I'm just running some random tests and I noticed that the minimap doesnt show up on all fights. I tried it on Ifrit ex and it showed up fine but on Sophia or Emerald Weapon, for some reason it doesn't show up. Am I using it wrong or not every fight has the boss radar implemented?

**Comment by Ants1988** [comment]
https://github.com/awgil/ffxiv_bossmod/tree/master/BossMod/Modules

That folder will give you an idea of everything thats currently supported.
