### ISSUE TITLE
plugin installed but no radar.

### ISSUE THREAD

**Issue by hughmangus** [awgil/ffxiv_bossmod#106]
plugin was installed by dalamud and can access it by /vbm
the problem there is no radar and matter what i do i can't make it appear, i'm using borderless with two monitors.
does the radar only appears when using it when it supports a certain content ?

**Comment by Makdag15** [comment]
Yes it only shows up for the following.

https://github.com/awgil/ffxiv_bossmod/tree/master/BossMod/Modules
