### ISSUE TITLE
Ban?

### ISSUE THREAD

**Issue by CountAlucard99** [awgil/ffxiv_bossmod#107]
Can I get banned if no one reported me?

**Comment by Ants1988** [comment]
I've been using it since Asphodelos and I haven't been caught or banned.

Don't tell anyone you're using it or show any screenshots with it active.

**Comment by ArmoredPuma** [comment]
Def agree to the comment above. As long as you doing talk about it or show it you should be good to go.

**Comment by Ants1988** [comment]
and don't stream or upload any content with it active.
