### ISSUE TITLE
(Multi-Monitor Mode) If minimap is in upper corner, overlaying the BM map is prohibited.

### ISSUE THREAD

**Issue by Nox13last** [awgil/ffxiv_bossmod#109]
My minimap is up in the corner.
![image](https://user-images.githubusercontent.com/1292492/217687396-dc91212b-25b6-449c-b742-c2f3f3a19da4.png)

I intend to overlay the BM over it. But because of the absurd amount of slack space given to the text cues...
![image](https://user-images.githubusercontent.com/1292492/217688221-83140162-8edf-4e05-9636-8d1ce40288e4.png)

...trying to move the BM map window to it causes it to escape the game window. If the game is running in Borderless Mode, this causes the minimap to be rendered completely invisible, and for the text queues to also be outside of the window (and at this point, probably in the dead-space above my monitor).
![image](https://user-images.githubusercontent.com/1292492/217688352-925a48ad-844f-453b-901d-c470a24247b4.png)

Can I suggest relegating the text cues to their own smaller window that can be moved independently of the BM map, and trimming the fat around the BM map?

(PS, thanks! This mod got me through my blind first-run of Aglaia! Duty Roulette do be like that sometimes.)

**Comment by ArmoredPuma** [comment]
Hey, sorry this isnt an answer to your question but what minimap/hug ui is that? its exactly what im looking for.

**Comment by Nox13last** [comment]
@ArmoredPuma 
Hi! No problem! It's _Material UI,_ (by Sevii and Skotlex - https://github.com/Sevii77/ffxiv_materialui_accent/raw/master/repo.json) piped through Penumbra (https://github.com/xivdev/Penumbra/raw/master/repo.json), with the following options set in Penumbra (as relevant to these screenshots):
- Minimap (Square - White Cardinal)
- Main Command Icons (Solid Background)
The minimap canvas is Moogle Maps (by Vec7rex), and the Daily Tasks that I forgot to remove before taking the screenshots is Daily Duty (by MidoriKami).

When using Material UI (it's a plugin), it will tell you that you will need to press the 'Rediscover Mods' button in Penumbra. Do _not_ forget to do this.
![image](https://user-images.githubusercontent.com/1292492/217956558-5f4c0968-77d8-455a-9e09-2da382c73b69.png)

I hope this answers your questions to your satisfaction.

**Comment by ArmoredPuma** [comment]
Ah tysm! :)

**Comment by Nox13last** [comment]
In the time it's taken this ticket to not receive a dev answer, I managed to get all 19 Manderville weapons and upgrade all of them to Amazing tier, and get all three Splendorous Tools and upgrade them to Crystalline.

I'm assuming, given the lack of dev replies and continuing updates regardless, that this ticket is de-facto #wontfix (or whatever the equivalent is for this repo).
That's a shame. I hope things work out.

**Comment by awgil** [comment]
Sorry for the lack of reply - completely missed this ticket.

The 'slack space' is needed for rotation - depending on the settings, map can rotate to match camera rotation - and in case of square arenas it means you need almost 1.5x the space the accommodate the map rotated by 45 degrees. Arguably, when minimap rotation is disabled, this 'slack space' can be removed.

Splitting stuff into multiple windows - ok, so I definitely prefer having everything in the same window - so I guess it has to be turned into an option. Managing windows is currently a bit of a pain the ass, but definitely doable. I'll think what I can do.

"Moving outside game window makes it invisible" - this I'll have to investigate, sounds like a bug. Will take a look - in the meanwhile, if you can describe in more detail what happens, it will simplify the investigation.

Reopening, since I'll probably do something to address the issues described here.

**Comment by Nox13last** [comment]
Hey, thanks for the reply. I hope my post didn't come off as snippy. This tab has been on my browser session for two months now with no signs-of-life.

- Slack space - Makes sense. It didn't occur to me that this would be necessary if the minimap is set to rotate.
- Splitting - Dalamud itself supports window-snapping - windows being docked to other windows as panes, or being conglomerated into a single window that has tabs. I don't use it often, but doing it that way seems like it would be clunky but serviceable, if one insists on using a single window.
- Transparency bug - I don't think this issue is with Bossmod exclusively. Every window that Dalamud has that purports to support transparency (that is, most of them) immediately becomes opaque as soon as it starts leaving the game window. This is only the case when the game is set to borderless or windowed, and a Dalamud window is moved outside of the game's bounds.
Normally, this isn't a problem, but when combined with Bossmod's "slack" (see above) and with my game's minimap being so close to the **one** edge of the screen that said slack aggravates _and_ with the game set to borderless (the performance of exclusive-fullscreen is just not worth having Windows's desktop window manager freak out **every time** I alt-tab to get Teamcraft or a wiki page up as I often do), the result is an opaque window hiding something behind it.
In the interim, I've had to move the Bossmod window under the minimap and sort of juxtapose the two maps in my head.

**Comment by awgil** [comment]
Added some options that can probably get you where you want (all in Boss module window settings):
1. Expand space reserved for map to allow arbitrary rotations: set by default, if cleared and map rotation is enabled, rotated square corners will be clipped
2. Show text hints in separate window: cleared by default

Also "Trisha mode: show radar without window" is probably what you want enabled too. For some reason, it doesn't work correctly for windows that are outside main game's window, but that's probably not an issue in your case.
