### ISSUE TITLE
Any new upcoming classes soon or in development for auto rotation?

### ISSUE THREAD

**Issue by ArmoredPuma** [awgil/ffxiv_bossmod#110]
Just like the title says, was just curious on what your thoughts were with new classes or if you had any intention on adding more as time went on. Id love to see a melee represented as well as you've done WAR and BRD.

**Comment by awgil** [comment]
I'm (slowly) leveling a DRG now, it's probably gonna be the next supported class.

**Comment by awgil** [comment]
Outdated.
