### ISSUE TITLE
"Cannot Use Yet" - on combat

### ISSUE THREAD

**Issue by dwfmagik** [awgil/ffxiv_bossmod#114]
Hi there,

I've enabled the plugin, and when entering combat (on Reaper level 86), it spams ''Cannot Use Yet'' - but im not sure what it's trying to do.

I've disabled EVERY 'option' in the menu, and it's still trying to do something in combat.

Any idea what? I'm after just the boss-aoe-frame, not so much any combat/rotation stuff.

Many thanks!

**Comment by awgil** [comment]
No idea, there is no autorotation for RPR anyway. You can try checking logs (see 'getting help' section on how to enable them), there might be something there.

**Comment by awgil** [comment]
Outdated.
