### ISSUE TITLE
Not visible in Dalamud

### ISSUE THREAD

**Issue by CureFlora** [awgil/ffxiv_bossmod#119]
I am 100% sure that I am doing everything right. Since, for example, the noclippy plugin was found immediately following the same instructions.

But I can't find this plugin.

**Comment by mokeling** [comment]
me too

**Comment by lemontea95** [comment]
is keep showing load error, unable to use or update any idea for this ?
![Capture11111](https://user-images.githubusercontent.com/2517315/229871254-1382da57-b5ed-44b1-8ddd-2dc572b27bd5.PNG)

**Comment by Constmar** [comment]
> is keep showing load error, unable to use or update any idea for this ? ![Capture11111](https://user-images.githubusercontent.com/2517315/229871254-1382da57-b5ed-44b1-8ddd-2dc572b27bd5.PNG)

getting the same issue

**Comment by User8455** [comment]
it is working now, ty ♥

**Comment by awgil** [comment]
Come on, folks, it's patch day - of course it wouldn't be working until I updated it...

**Comment by Constmar** [comment]
thank you!

**Comment by CureFlora** [comment]
> Come on, folks, it's patch day - of course it wouldn't be working until I updated it...

thank you))

**Comment by lemontea95** [comment]
> Come on, folks, it's patch day - of course it wouldn't be working until I updated it...

Thank You so much!
