### ISSUE TITLE
Streamer mode

### ISSUE THREAD

**Issue by xVenora** [awgil/ffxiv_bossmod#120]
would it be possible to add a feature to make the radar invisible to streams such as on obs and discord

**Comment by CureFlora** [comment]
> would it be possible to add a feature to make the radar invisible to streams such as on obs and discord

Does this plugin work for you? Just not visible in Dalamud

**Comment by xVenora** [comment]
> 

it does not

**Comment by DatGoose** [comment]
Just don't monitor capture, if you are using OBS it doesn't need to inject to the game. If you game capture then you won't capture any overlays.
