### ISSUE TITLE
Is it possible to add "Auto face away from target" to jobs not supported by auto rotation?

### ISSUE THREAD

**Issue by haganebr** [awgil/ffxiv_bossmod#121]
I noticed that when playing BRD or WAR with auto rotation on, I can keep attacking while facing any position. I know auto rotation is pretty hard to program, but would it be possible to add just that to other jobs? Would really help with P8S snakes and TOP monitors.

**Comment by xVenora** [comment]
auto rotation doesn't work for me anyway

**Comment by awgil** [comment]
That's a reasonable request, I think it makes sense that some features that are currently tied to autorotation are made independent:
1. Animation lock reduction a-la xivalex/noclippy.
2. Movement lock/slidecast assist.
3. Keeping orientation after attacks.

I'll see whether I can do that next time I touch relevant code.

**Comment by awgil** [comment]
Done - moved all relevant config options from "autorotation" to "action tweaks" category; they now all should work even if autorotation is disabled (or not implemented for given class).

**Comment by haganebr** [comment]
I tested out the option and it only works for the very first attack on melee or physical ranged attacks. Every attack after that leaves me facing my target afterwards. Actions with cast timers work correctly.

**Comment by awgil** [comment]
That's weird - sometimes after rotation restore it is snapped back on next frame. This never happened with autorotation enabled for some reason, but happens relatively consistently without it. I don't really understand what's going on, but I added a confirmation that rotation stays 'restored' for an extra frame. Let's see how it goes...
