### ISSUE TITLE
P8S FF

### ISSUE THREAD

**Issue by Seiyus12** [awgil/ffxiv_bossmod#124]
Hi so I’m not sure how to replicate the issue or when it happens but basically there are times where during Fourfold only 1 half of the aoes are displayed. Not sure if anyone else had this problem.

**Comment by awgil** [comment]
If you can reproduce that consistently, best way to find the problem would be the following:
1. Next time you go to P8S, enable world state logging (options -> general -> dump world state events)
2. Reproduce the problem
3. Send me the log (found in C:\Users\username\AppData\Roaming\XIVLauncher\pluginConfigs\BossMod\) and tell the approximate time of the pull when the issue happened.

**Comment by Seiyus12** [comment]
I'll keep that in mind, it rarely happens but when it does, it catches me off guard.
