### ISSUE TITLE
P5S Ruby 6

### ISSUE THREAD

**Issue by Seiyus12** [awgil/ffxiv_bossmod#125]
I noticed during Ruby 6 for P5S, only 1 square out of the 3 that explode from the yellow crystal gets highlighted. It happens consistently, so I'm not sure if you need the logs like you said for my P8 question.

**Comment by awgil** [comment]
Well, that's the mechanic - one square is guaranteed unsafe (has 3 crystals), other 3 have 2 crystals each, selecting which one to recolor is arbitrary. I don't really remember what is the standard way to select one (across unsafe? or some priority scheme? different for different DCs?).

That said, there is a bug right now - the component doesn't work correctly unless stars align. I've committed a fix, it will be available in the next version.
