### ISSUE TITLE
Blm Auto-rotation 

### ISSUE THREAD

**Issue by Stryker627** [awgil/ffxiv_bossmod#126]
I tried this on my black mage that was only lvl 50, it seemed to work fine....... then i level skipped to 80, now it will not load, is there something I can do to fix this?

**Comment by awgil** [comment]
Monk is in the same state as blm - was working up to L50 last time I checked (few months ago), but nowhere near polished.

Don't think there's any way to expedite that - I'm writing modules as I'm leveling classes. Next would be DRG, then probably BLM.
