### ISSUE TITLE
How do I edit my planned cooldowns?

### ISSUE THREAD

**Issue by DemacianEmpress** [awgil/ffxiv_bossmod#132]
I play WHM and I was wanting to try out the cooldown planner, but whenever I open the window, all I see is a scrollable list of fight mechanics. There is nothing that is clickable or editable outside of the buttons and slider at the top of the window. Am I missing something here? Any help you can offer would be nice!

**Comment by awgil** [comment]
Try different class (WAR or BRD). WHM is in a bad state autorotation-wise.
