### ISSUE TITLE
White circles (Suggestion; Not An Issue)

### ISSUE THREAD

**Issue by Seiyus12** [awgil/ffxiv_bossmod#133]
Would it be possible to add the white circles that pop up whenever you hit skills while using auto rotation? (Currently the skill gets pressed without you knowing what was pressed - bard)

**Comment by awgil** [comment]
Not sure what do you mean by "white circle".

Currently, you can see "what was pressed" by animation and by flying combat text. You can see what is "about to be pressed" if you enable autorotation UI - the first row is the name of the next planned action.

One improvement that I'd definitely want to make is to show some indication for missed/succeeded positionals for melees, though I didn't decide how to best show that. I was also thinking about adding some sort of a 'timeline' that shows some past and future actions - that could be made independent from actual autorotation (if you prefer pressing buttons manually, but still want hints) - but there are some complications for that idea (currently all autorotation modules select best action based on current state only, they don't do any predictions).

**Comment by Seiyus12** [comment]
The timeline idea would be a nice addition. And another way to put it is that whenever you're mashing a skill, the inner white circle that appears every time you're clicking the skill. I wanted to know if something like that was possible to be added. It's nothing too serious. Example https://www.youtube.com/watch?v=UfPkSTkolPw - That's just a random rotation video and not the large white CD circle, the one you see popping up whenever she's spamming the skill.
