### ISSUE TITLE
[Bug] Boss module ARR T04Gauntlet pops in unrelated instances

### ISSUE THREAD

**Issue by bluesolei1** [awgil/ffxiv_bossmod#137]
Boss module ARR T04Gauntlet pops in unrelated instances. So far noticed it pop in these dungeons:

1. Haukke Manor (Hard) 
2. last two bosses in Weeping City of Mnach
3. The Sunken Temple of Qarn (Hard)
4. The Wanderer's Palace (Hard)
5. Containment Bay P1T6 (Extreme) 
6. Syrcus Tower
7. Halatali (Hard)

Module window upon loading into Haukke Manor (Hard):
![image](https://user-images.githubusercontent.com/42896692/235442812-88478fac-8d03-40f8-8532-3ae305186f7e.png)

**Comment by awgil** [comment]
Yeah, that's unfortunate - will fix in the next version.
