### ISSUE TITLE
Summoner Autoration stopped working

### ISSUE THREAD

**Issue by Poster23242** [awgil/ffxiv_bossmod#138]
It appeared to work fine prior to today.  The box that shows which spells is being cast doesn't show up either. Logs are attached.
[dalamud1.log](https://github.com/awgil/ffxiv_bossmod/files/11433460/dalamud1.log)

**Comment by awgil** [comment]
There is no SMN module, and never were - not sure what was even 'working' before.

**Comment by Poster23242** [comment]
What is SMN under autoration then?  I'd go in and provide a screenshot, but im no longer subbed.  either 1) you know that is there and just mean it doesn't work, or 2) i'm s

**Comment by Poster23242** [comment]
There is an SMN under autorations.

**Comment by awgil** [comment]
Huh, actually, you are right, it is there - I completely forgotten about its existence. It's only up to level 30 though.

**Comment by weapi1** [comment]
If I may make a suggestion, perhaps it would be a good idea to add up to which level the autorotation is currently supported next to the class in the UI to avoid a bunch of confusion and a lot of issues being opened in the future
