### ISSUE TITLE
Request For MCH Auto Rotation 💓

### ISSUE THREAD

**Issue by StaticSadness** [awgil/ffxiv_bossmod#139]
Hiya! Would you ever consider doing a BRD equivalent Auto Rotation for MCH? I mainly use the auto rotation feature for ultimate raid progging so i can focus on mechanics better or sometimes for boring expert roulette! I love the way bard plays in with the auto rotation it’s very clean and i was thinking because mch is basically the exact same as bard would it be hard to do it for level 90? I like the weapons and the damage is a little better on mch 🙏🏻🙏🏻🙏🏻Please consider

**Comment by awgil** [comment]
I don't have MCH leveled - when I get around to leveling it, i'll create a module for it - that won't happen soon though, I'm afraid.

**Comment by StaticSadness** [comment]
> I don't have MCH leveled - when I get around to leveling it, i'll create a module for it - that won't happen soon though, I'm afraid.

💔💔💔

**Comment by Hsady** [comment]
I'd kill for mch autorota. T-T

**Comment by StaticSadness** [comment]
Ikr I’d pay money for it please make it happen we beg I’ll pay you

**Comment by awgil** [comment]
Outdated.
