### ISSUE TITLE
Autorotation doesnt wait for pull timer as of 6.4 (BRD)

### ISSUE THREAD

**Issue by weapi1** [awgil/ffxiv_bossmod#140]
As of the last update pressing burst shot during countdown will instantly pull the boss rather than queuing the auto rotation for when the pull timer ends as it used to.

**Comment by awgil** [comment]
Can't reproduce - this works correctly for me, on the dummy at least. Please attach the log (see readme for details on how to enable it) and tell me what exactly you're doing (which boss/instance, do you start the countdown or someone else, etc.)

**Comment by weapi1** [comment]
Can confirm as working now as of the maintenance. I'm not sure what has caused it to malfunction earlier nor do I have logs, however I did test it with a dummy (myself starting the countdown) and in the new ex (other people starting the countdown) and it instapulled.
