### ISSUE TITLE
Deep Dungeon Compatability?

### ISSUE THREAD

**Issue by ax5nonymous** [awgil/ffxiv_bossmod#147]
Are there plans to add compatability for deep dungeon bosses like EO?

**Comment by awgil** [comment]
I plan to, eventually. For now the immediate plans are new savages (I'm currently still progging P12, so don't have much time to work on plugin), then remaining ultimates (DSR/TOP/UCOB), then probably new criterion, then probably deep dungeons.

**Comment by awgil** [comment]
Outdated.
