### ISSUE TITLE
Great Job

### ISSUE THREAD

**Issue by hokeenthong** [awgil/ffxiv_bossmod#15]
Sorry I am not indicating an issue and I do not know how to provide you with feedback so I am doing it here. 

This is a great addon to the game man. Really appreciate your work and you have made the game a lot more fun for me. I hope a lot of others find this too. I do not know any computing language but let me know how I can help to support you. Perhaps you can start a discord site to garner more help and support. 

In any case, great job!!!!

**Comment by Linoa235** [comment]
I totally agree with what you just said! undiscord to help will be nice, I've discovered the game in a different light since I've been using it. this is exactly the kind of plugin I'm looking for! great job !

**Comment by Linoa235** [comment]
> Créer un discord n'est pas un problème, mais je n'ai aucune idée de comment l'organiser, quel type de discussion devrait être là et ainsi de suite. En fait, je suis assez surpris qu'il y ait des utilisateurs, étant donné que je n'ai jamais annoncé ce plugin nulle part, il n'y a pas de documentation appropriée ou même une description décente, et en général c'est assez inachevé et de qualité alpha...

You can be sure that this kind of plugin for FF14 and search for a lot of players. I stumbled upon your mods after many years of research folks who kind of plugin keep it private. and I think over time a lot of people will love you for this kind of work on FF14

**Comment by hokeenthong** [comment]
I am not sure if it is me but to me, your addon is so innovative and take raid assistance to a different perspective and in my opinion it would help so many people. I do not know your motivation, if any but if you need any help to further this, a discord page would attract similar minded people to develop this and an avenue for me to show my appreciation. In any case, you are doing a great job and I only hope this will not end here. Thank you again.

**Comment by cidoliveira** [comment]
@awgil Me and all my friends use this plugin and it makes it possible for a disabled static member to properly feel safe and enjoy endgame content. You're doing an amazing work and I'd love to join some kind of community to discuss the mod and keep up with your upcoming plans. Please keep at it, it's helping more people than you even know!

**Comment by awgil** [comment]
Re new ultimate - I'm on vacation right now, plan to start working on it when I return. That it, unless my static turns out to be a bunch of pussies - there's been some whining on discord that it looks too hard and maybe we should go for other ultimates first - that would suck, I would probably have to look for some other static to take me in, so that I can gather relevant data :D

**Comment by cidoliveira** [comment]
Honestly old ultimates bossmod would be great, too! Imagine having TEA or UCOB modules, it'd be lifesaving;

**Comment by awgil** [comment]
Yeah that stuff is definitely coming someday, though I'd rather prioritize new ultimate tbh

**Comment by Linoa235** [comment]
> Ouais, ce truc arrivera certainement un jour, même si je préfère donner la priorité à un nouvel ultime tbh

very cool !!!

**Comment by hokeenthong** [comment]
> 

Enjoy your vacation man. Will look forward to your update on the new ultimate when you are back and ready. Thanks again!!!!

**Comment by hokeenthong** [comment]
Do you have Ko-fi or something? I want to show my appreciation. Your updates to DSR are sooo good.

**Comment by awgil** [comment]
> In any case, your static should know that with this add-on, they should not have any problem.

Hah, if only - half of them just refuse to use this addon, others tuck it somewhere into corner and say that "it's not convenient" to look there :D

> Do you have Ko-fi or something? I want to show my appreciation. Your updates to DSR are sooo good.

No idea what are you talking about :)

**Comment by Linoa235** [comment]
I'm not going to redo a post just to answer this one, I want to say thank you for this magnificent plugin which helps a lot of people enormously, and I want to congratulate your work and its future evolution I hope you will continue to add lots of other stuff, etc...

I wish you a good end of the year 2022 to you :)
