### ISSUE TITLE
Bard Autorotation

### ISSUE THREAD

**Issue by Seiyus12** [awgil/ffxiv_bossmod#151]
The bard auto rotation usually started with raging strikes as the first buff but the last couple of days it randomly starts with mages ballad and ignores the battle voice, raging strike and barrage. Not sure if anyone else is experiencing this but it happens randomly.

**Comment by Stryker627** [comment]
I have not experienced this.

**Comment by Seiyus12** [comment]
I'll try to get it to happen again if I can and record my screen with the skill display from ACT, for now I seem to be back to normal
