### ISSUE TITLE
Radar not showing

### ISSUE THREAD

**Issue by skedoodlez** [awgil/ffxiv_bossmod#156]
Hi, I installed Bossmod but the Radar is not showing up. I read the previous comments and checked that Enable boss modules are activated and only when I press ( show boss module demo out instances ) does the radar show up. I don't know if my problem is with the screen resolution because its in borderless.

**Comment by skedoodlez** [comment]
[dalamud.log](https://github.com/awgil/ffxiv_bossmod/files/11992464/dalamud.log)

**Comment by awgil** [comment]
Which boss do you expect it to see on? It very well might be that there is no module for it. Try something like EW savages/extremes and see whether it works there.

**Comment by skedoodlez** [comment]
> Which boss do you expect it to see on? It very well might be that there is no module for it. Try something like EW savages/extremes and see whether it works there.

Thanks I will quickly have a look and let you know.

**Comment by skedoodlez** [comment]
Last night I did the new extreme and it didn't work. I also did an Alliance Raid and it didn't show up.

**Comment by skedoodlez** [comment]
Never mind I managed to solve the problem. I was a dummy thanks for the great add on :)
