### ISSUE TITLE
BRD  auto rotation issues 

### ISSUE THREAD

**Issue by Kingudabat** [awgil/ffxiv_bossmod#157]
Yesterday I was testing several times and noticed several inconsistencies. 

1- for some reason sometimes the minute burst was not done. 

2- In non-specific situations, the 2 minute burst did not work or, in default, a delay was made. 

3- between 6 and 8 triple weavings were made. 

I had test several times in the dummy and I didn't see major problems, but in duty I managed to see these errors. Either with or without a planning cooldown.

I doit on p9s, p10s, and p11s.

**Comment by haganebr** [comment]
To add on to this: Sometimes it will quickly use Wanderer's Minuet and Mage's Ballad in quick succession during the opener.

**Comment by awgil** [comment]
Can you provide any of the logs when these mistakes happen? Make sure that autorotation->log messages option is turned on, and then follow instructions in readme.

I didn't personally see any of these problems, but some more specific questions:
1. What exactly do you mean by a minute burst? Sidewinder?
2. What exactly happened when 2-minute burst didn't happen? The conditions are a bit complicated (WM is late-weaved, then RS should happen on next ogcd slot, then there are some quite complicated conditions for BV+RF, they are explained in BRDRotation.cs, but it is entirely possible that I've made some mistakes there...)
3. Triple weaves on BRD should not happen for rotational abilities (but note that if you press an ogcd manually, it would happily triple weave it if it thinks it can get away with it without delaying gcd!), but I'll need to look at the log to really understand what's happening. What's your SKS btw?
4. Two songs in short succession is very weird, could be some lag related problem that I've never seen before, but I'll also need logs to investigate.

**Comment by haganebr** [comment]
Regarding 4. it stopped happening once I started using exitlag. I used to play at 200ms ping, now at 120-ish. My guess is it would be something related to that. Unless something changed in the code?

**Comment by awgil** [comment]
Outdated.
