### ISSUE TITLE
Monk autorotation don't work anymore ?

### ISSUE THREAD

**Issue by Romaain002** [awgil/ffxiv_bossmod#159]
Hi hi !

When I tried to play Moine, I noticed that the autorotation was no longer working. Is this a problem on my side or yours?

(I'm LvL 64 with my Monk)

**Comment by weapi1** [comment]
Monk autorotation isn't supported past lvl 50 or 60, not sure.

**Comment by Romaain002** [comment]
Well, 63 it work, 64 it don't work !

Thank you for your response mate !

**Comment by awgil** [comment]
That is right, MNK is not really implemented above L50, it will automatically disable shortly after. That's planned for relatively distant future.
