### ISSUE TITLE
P12S Pangenesis

### ISSUE THREAD

**Issue by jbk321** [awgil/ffxiv_bossmod#160]
Most raids on PF seem to use 2+0 conga strat per pastebin. Anyway we can switch strats and have indicators set differently? As of currently in bossmod I see 1 stacks join the first towers instead.

**Comment by awgil** [comment]
Please link the description of the strats, I'll look into implementing that. FWIW I've only killed P12 with my static, which used some early strats, so I'm not aware what PF does.

**Comment by Flavescent** [comment]
@awgil - I'd also appreciate an option to enable the 2+0 strat, which is the more commonly used one in PF.

It is described here:

- https://raidplan.io/plan/ufvBPVEMXJEpfC83 p. 10 et seq.
- https://www.youtube.com/watch?v=O3_V1DwPA1I at 14:30

Also, thank you for this very helpful mod!

**Comment by awgil** [comment]
If I understood the strats correctly, there are actually 2 arbitrary assignments:
1. Whether first tower on each side is soaked by 0-stack or 1-stack player (second soaker is always 2-stack player with short debuff).
2. Whether leftover players (not soaking first tower and not with long debuff) soak northern or southern tower from the second set.

This gives four possible combinations, two of which are standard '2+0' and '2+1' strats (but other two are also valid) - is that right? Or do these remaining combinations not work for some other reason (e.g. slimes not spawning or smth else)?

(Technically I guess one could also assign long debuffs to soak northern tower on the opposite side, but that would be weird and I doubt anyone does that)

**Comment by awgil** [comment]
For now, added a single 2+0 vs 2+1 selector.
