### ISSUE TITLE
Autorotation "Target not in range" error after using duty actions and facing away from target.

### ISSUE THREAD

**Issue by haganebr** [awgil/ffxiv_bossmod#161]
After using any duty action during auto rotation AND facing away from my target, skills stop going out, instead giving me a "Target not in range" error. I tried it with both WAR and BRD and could easily reproduce it.

One easy way to test is going to Emanation (Extreme) and popping Vril, then facing away from the boss. I'm doing all this on controller, but should happen on M+KB as well.

Relevant logs during my testing:

> 2023-07-24 08:52:12.645 -03:00 [DBG] [BossMod] Condition chage: InCombat=True
> 
> 2023-07-24 08:52:14.622 -03:00 [DBG] [BossMod] [AMEx] UAL #233 (Spell 31 'Heavy Swing' @ 4000C850 / [0,00, 0,00, 
> 
> 2023-07-24 08:52:14.995 -03:00 [DBG] [BossMod] [AMEx] AEP #233 0,136 -> ALock=0,388 (delayed by 0,364-0,000), 
> 
> 2023-07-24 08:52:15.378 -03:00 [DBG] [BossMod] [AMEx] UAL #234 (Spell 52 'Infuriate' @ 1073F3A8 / [0,00, 0,00, 0,00] 
> 
> 2023-07-24 08:52:15.937 -03:00 [DBG] [BossMod] [AMEx] AEP #234 0,000 -> ALock=0,269 (delayed by 0,500-0,000), 
> 
> 2023-07-24 08:52:19.985 -03:00 [DBG] [BossMod] Condition chage: Jumping=True
> 
> 2023-07-24 08:52:20.752 -03:00 [DBG] [BossMod] Condition chage: 47=True
> 
> 2023-07-24 08:52:20.752 -03:00 [DBG] [BossMod] Condition chage: Jumping=False
> 
> 2023-07-24 08:52:21.459 -03:00 [DBG] [BossMod] Condition chage: NormalConditions=False
> 
> 2023-07-24 08:52:21.459 -03:00 [DBG] [BossMod] Condition chage: Unconscious=True
> 
> 2023-07-24 08:52:21.459 -03:00 [DBG] [BossMod] Condition chage: BetweenAreas=True
> 
> 2023-07-24 08:52:21.459 -03:00 [DBG] [BossMod] Condition chage: 47=False

**Comment by weapi1** [comment]
Noticed this a lot while doing the new criterion, can recreate, autorotation just stops once you face away even if you are on bard

**Comment by awgil** [comment]
Sorry, can't reproduce it, I assume I'm doing something wrong.

Do you have 'restore rotation' and/or 'sticky auto actions' settings enabled? What *exactly* do you do? (e.g. the emanation trial starts from 2 adds - do you do that while fighting adds?)

**Comment by weapi1** [comment]
I believe I have found the cause of this issue after some testing. 

It seems to be a conflict between Boss Mod and one of the ReAction features, the feature is called "Enable Enhanced Auto Face Target". What it does essentially is remove the autoface target on spells that don't require it such as some healing spells. It does not matter if I have restore rotation on or off, either way it seems to confuse it. As soon as I turn the ReAction option off, it works just fine. The way you can reproduce it is by turning on the ReAction feature, then pressing burst shot and activating Vril so it's weaved into the rotation, as soon as you do that, when you face away from the enemy, the autorotation just stops, as soon as you turn back towards the enemy it resumes. 

I am not an expert in this by any means, I just found this out by testing random things that could possibly be the cause.

I can also provide a recording of the said issue if you still can't reproduce it, but I would prefer to do so on discord or somewhere private as it would include in-game names, etc.

**Comment by awgil** [comment]
Ok, it sounds like compatibility problem with ReAction. I'm not really aware what that plugin does, but from the short look it seems that it and autorotation/action tweaks part of this plugin are trying to touch similar things - so it might be best not to try to combine them.

Did anyone see this problem without ReAction?

**Comment by haganebr** [comment]
I was away from my computer for a bit, but just tried disabling the ReAction feature and the problem seems to be solved. Closing the issue for now.
