### ISSUE TITLE
[Suggestion] Option to not triple weave / clip GCDs on the cooldown planner

### ISSUE THREAD

**Issue by lazylemo** [awgil/ffxiv_bossmod#162]
Great addon just a slight problem with the cooldown planner as to when things are used.

**Comment by awgil** [comment]
It should never clip GCDs, but depending on the settings (e.g. if you use xivalex/noclippy/built-in alternative) it could triple-weave. If you have any logs where addon triple-weaved and that resulted in clipped GCDs, please share, I'll take a look.

**Comment by lazylemo** [comment]
I kind of figured it out myself using High priority/Low priority (high priority being to enforce no matter what the ability even to clip or not) so that works! Could i also ask to not track lets say SMN raid buff? since its earlier than any other raid buff, thanks again for the amazing work

**Comment by awgil** [comment]
Even high priority should not clip GCDs, something's not right. The priority is planned oGCD vs normal rotational oGCD (e.g. if you play a WAR and have a situation where planner wants to use vengeance, but upheaval is off cd, the priority order is vengeance if high-prio > upheaval > vengeance if low-prio; same for other classes/abilities).

Not tracking SMN - not sure about that tbh, what if your only raidbuffs in the raid are from SMN? Raid buff tracking in general is not ideal (e.g. it should handle various degenerate cases, like people fucking up their rotations and drifting raidbuffs), if you're playing in a static and everyone plays well, you might be able to just fine-tune your rotation in a planner for each fight. Hmm I think, for a simple config, I can just expose a bunch of checkboxes (which buffs to consider as raidbuffs) - I'll think more about it...

**Comment by awgil** [comment]
Outdated.
