### ISSUE TITLE
Issues with vbmai commands

### ISSUE THREAD

**Issue by iRobsie** [awgil/ffxiv_bossmod#163]
Hey! Love this tool, and the convenience it brings, it's truly incredible. I've tried dipping my toes in the water with the AI section of it, despite being not fully developed, but I noticed it had some commands in the code, such as swapping a master, and cancelling the ai mode.
I jumped into a party with my alt account, and attempted to swap masters but it failed to do so, but running vbmai cancel, indeed cancels the ai on both sides. Neither was able to take master control with vbmai follow though.

**Comment by awgil** [comment]
Yeah AI mode isn't really well developed, at least for now.
