### ISSUE TITLE
Triple weaving/Action tweaks.

### ISSUE THREAD

**Issue by lilwayne2017** [awgil/ffxiv_bossmod#164]
i havent found informaton about this so i'm asking here, under the section "Action tweaks" there are options that remove animation lock to a level that allow us to triple weave, i just want to know, can i get banned for triple weaving, or even "late double weaving"? (Banned either in game or fflogs).

Does triple weaving exist without puggings in this game? ( i have been using both said tweaks, but i only double weave cause i'm "scared")

Btw, this plugin is perfect, thank you very much for developing it.

**Comment by Niahmi** [comment]
So:
Will you get banned by SE? very unlikely. It's a risk with any third party tool, but those are the risks that you run.

Will you get banned by FFlogs, potentially. I just tried this option out to test the numbers and it's _very_ aggressive (50+ instances of 0.53X). It's consistently giving 0.53X weaves; by default is 0.625 and with some server jank or tools like alex/noclippy, 0.583 (You wouldn't be banned for one log. If you keep uploading bad logs though, they would consider it. One dodgy log would get blacklisted and that would be the end of it. 0.53X is technically possible, but we're talking single digit ping and a JP connection. 

For now, you're probably better off using XIVAlex or NoClippy for animation reduction.

**Comment by lilwayne2017** [comment]
> 

Not even with "0 ping"?

**Comment by lilwayne2017** [comment]
> > So: Will you get banned by SE? very unlikely. It's a risk with any third party tool, but those are the risks that you run.
> > Will you get banned by FFlogs, potentially. I just tried this option out to test the numbers and it's _very_ aggressive (50+ instances of 0.53X. For comparison with NoClippy, I had 1 instance of 0.53). It's consistently giving 0.53X weaves; by default is 0.625 and with some server jank or tools like alex/noclippy, 0.583 (You wouldn't be banned for one log. If you keep uploading bad logs though, they would consider it. One dodgy log would get blacklisted and that would be the end of it. 0.53X is technically possible, but we're talking single digit ping and a JP connection.
> > For now, you're probably better off using XIVAlex or NoClippy for animation reduction.
> 
> How aggressive is Clippy/Alex in comparison?
> 
> People aren't getting fflogs banned for Clippy/Alex afaik.

Dont they flag the ones with "0 ping"? (i'm talking about xivalex in that case)

**Comment by Niahmi** [comment]
> How aggressive is Clippy/Alex in comparison?
> 
> People aren't getting fflogs banned for Clippy/Alex afaik.

Clippy & Alex usually give me consistently 0.625 and the occasional 0.58X weaves. 0.58 is rather on the edge of what FFlogs considers reasonable; and wouldn't cause a ban from their site. To quote Kihra on it "0.53 is far beyond murky territory though". I mentioned it initially but with clippy I get maybe one 0.53X weave in a ~10 minute fight, maybe 2-3 with Alex & 50+ with this one. 

They don't, as far as I'm aware, auto-flag any logs, but by nature of what it allows it can be reported to them, where a one off here or there would get blacklisted; while repeated logs of that nature would get you banned from their site as it's considered impossible to do consistently. It's unlikely that will happen, but if you start posting 99s & 100s where people start looking at your log, it'll be very obvious and _might_ lead to a ban from their site.

**Comment by awgil** [comment]
What do you mean by 0.58X? The default animation lock for most instant casts is 0.6s, so without any plugins you'll typically see ~0.65-0.7s delay between instants.

Currently this plugin removes all 'extra' animation lock delay, but still it should never reduce it below whatever ability is supposed to have (that is, below 0.6 for most instants).

One thing I can do is add another option that caps delay to some value (e.g. to 0.05s, so that all normal abilities would have 0.65s effective animation lock). Open to suggestions on the UI for that (turn on/off checkbox into off/perfect/0.05s combo? slider?)

Note that triple weaving would be possible if extra delay is <= 0.025s, less if you have any SKS (for triple weave to be possible, you need to fit 4 animation locks into GCD, meaning for 2.5s gcd effective animation lock should be <= 2.5/4 == 0.625).

**Comment by lilwayne2017** [comment]
> 

So that would mean that this plugging doesn't allow anything that a low enough ping/ perfect fps wouldn't allow? If so, is it "fflogs safe"?
Btw, maybe something that could cause issues would be using XIVALEXANDER + the animation tweaks from this mod (idk tho).
Great pluggin again, thank you very much.

**Comment by awgil** [comment]
> So that would mean that this plugging doesn't allow anything that a low enough ping/ perfect fps wouldn't allow?

Kind of - that also assumes 'perfect' (immediate) server response, which doesn't really happen because of finite server tick rate.

Using that together with xivalex/noclippy though is definitely NOT recommended, since they would both reduce animation lock. Select one or the other.

**Comment by awgil** [comment]
Outdated
