### ISSUE TITLE
Plugin not show in dalamund since update

### ISSUE THREAD

**Issue by Miku13012** [awgil/ffxiv_bossmod#167]
Hey, since the update today 6.48, the plugin had an error in dalamund, i tried to delete and reinstalle, but now its not even show in dalamund anymore, tho it was updated cause i saw "[Opcode update for 6.48)

**Comment by Flavescent** [comment]
Same issue here. After starting the game with Dalamud Beta, the plugin is listed with the error message "failed to load". After deleting it and restarting the game, it cannot be found for reinstallation.
