### ISSUE TITLE
BRD, DRG, BLM, MNK, SMN as of patch 6.48

### ISSUE THREAD

**Issue by PepsiTyler** [awgil/ffxiv_bossmod#168]
Bard (Level 80):
-Quick Nock (AoE) performs single-target rotation instead.

Dragoon (Level 80): 
-Single-target combo lets both DoT and personal buff drop.

Black Mage, Monk, and Summoner:
Do not function.

**Comment by Hsady** [comment]
Bard works fine for me, checked in Zadnor.
Monk works until level 50-something only, Summoner until around level 30? With the Black Mage I'm not sure.

**Comment by PepsiTyler** [comment]
Are there any known plugins that are incompatible with bossmod? because i don't know why this would be happening. 
[Video of Black Mage and Bard Auto Rotation issues](https://youtu.be/d6fRUPizrlo)

**Comment by weapi1** [comment]
Black Mage doesn't work past like level 50 or something, summoner doesn't work past level 30.

**Comment by awgil** [comment]
Only WAR and BRD are well supported for now. DRG should kinda work, but I expect bugs there - I'm planning to fix that at some point, once I level it up and play a bit at cap. Others are really not in a usable state, at least above 30/50.

Judging from the comments, I assume that BRD works fine? Closing on that assumption, please reopen if there are issues with BRD.
