### ISSUE TITLE
Wyrmwind Thrust not casting on DRG AI/Auto Rotation where level appropriate. 

### ISSUE THREAD

**Issue by ShiftyKiwi** [awgil/ffxiv_bossmod#176]
Hello, 

Using either of these features at level 90 on Dragoon seems to be bugged when it comes to Wyrmwind Thrust. For whatever reason the single target and aoe rotations on either of these features will work, except for when it comes to casting this spell.

**Comment by weapi1** [comment]
DRG is not yet fully supported or supported at all past level 80

**Comment by awgil** [comment]
Outdated.
