### ISSUE TITLE
Euphrosyne - Halone - Phase 2 not loading sometimes

### ISSUE THREAD

**Issue by Valmere** [awgil/ffxiv_bossmod#177]
Sometimes after the transition from the add phase (where she summons those spears) the module won't register that the boss is back in the arena and won't show any further warnings on the overlay. Doesn't happen every time but often enough to make a bug report about it.

**Comment by CarnifexOptimus** [comment]
do you have a replay for this

**Comment by awgil** [comment]
Should be fixed now in latest version.
