### ISSUE TITLE
Broken "Prevent movement whiles casting"

### ISSUE THREAD

**Issue by Eclipsum** [awgil/ffxiv_bossmod#18]
After the patch it seems to no longer prevent me from moving.

**Comment by awgil** [comment]
Are you sure the rest of the mod was working? I've just tried it and it worked fine for me...

If so, please attach dalamud.log file (found at C:\Users\username\AppData\Roaming\XIVLauncher)

**Comment by Eclipsum** [comment]
had to make a copy as github does not support OLD files
_dont mind all the plugins,its for testing purposes_
[dalamud log copy.txt](https://github.com/awgil/ffxiv_bossmod/files/8863807/dalamud.log.copy.txt)

**Comment by McSlothy** [comment]
Having the same issue. 

https://streamable.com/zm4zyt

In the clip i have all combat affecting plugins disabled (xiv combo, reaction, no clippy, redirect). I also tested afterwards with all plugins disabled not just the combat ones.

Dalamud console shows up this https://i.imgur.com/10z8l6a.png

**Comment by McSlothy** [comment]
I think i figured out the problem. I disabled Dalamud Beta and now it's working, 

There is a very minor stutter on some spells, but thats a minor thing. Basically movement stops before the check if the next spell is instant or cast-able.(if under swiftcast/triplecast/some smn spells) Once the plugin knows next spell is instant the movement resumes. It's just a split second.

Apologies.

**Comment by awgil** [comment]
Logs have 'Unexpected action-cancel (141): currently 0 are pending' message - which is weird, apparently cast-start isn't detected properly.

**Comment by awgil** [comment]
The stutter - this is a bug, I'll have to fix it - should be checking for swiftcast-like buffs.

**Comment by awgil** [comment]
Yeah apparently dalamud recently stopped dispatching client-initiated network messages, which broke various stuff in autorotation.

Fixed this by adding custom hooks for same functions.
