### ISSUE TITLE
read/help

### ISSUE THREAD

**Issue by lucy2000** [awgil/ffxiv_bossmod#182]
hi i wonder if you can help me...am new to the plugin do you have a actual list on all your dungeon's or trials it actually works on? or does it only work on some? if so what are the trials etc...

**Comment by weapi1** [comment]
You can look at the modules in the code and see which files are there and for what fights

**Comment by awgil** [comment]
Yep, there's no list (at this moment at least) - but you can look at the Modules directory in the code, it is organized quite intuitively, so should be simple to figure out what's working and what's not.

**Comment by lucy2000** [comment]
when you updating the plugin? or you waiting for 6.5?
