### ISSUE TITLE
Radar's not working in Steam deck with xivlauncher

### ISSUE THREAD

**Issue by gaoyike** [awgil/ffxiv_bossmod#183]
Everything looks good.
The auto rotation is working as expected.
However, in the windows, it shows: cur: inactive, for all bosses

I am using English version and playing in U.S server

**Comment by awgil** [comment]
What boss are you trying it on?

I'll need a log to debug this - see main page for details on how to grab one.

**Comment by awgil** [comment]
Outdated.
