### ISSUE TITLE
list of current supported content?

### ISSUE THREAD

**Issue by Theletha** [awgil/ffxiv_bossmod#185]
Hi is there a list somewhere to see the current supported content/bosses? or is the "Encounter-specific settings" the correct list of all content it has? since i dont see ex4 there?

**Comment by Niahmi** [comment]
You can check the supported content in the modules section on github. If you're unsure where to find that, here's a [link](https://github.com/awgil/ffxiv_bossmod/tree/master/BossMod/Modules).

**Comment by Theletha** [comment]
perfect thanks !!!
