### ISSUE TITLE
actions without target

### ISSUE THREAD

**Issue by cptn-cosmo** [awgil/ffxiv_bossmod#186]
Hi! It would be nice if hotbars would work normally without anything targeted, which wou0ld allow me to pull with AOE abilities like overpower by just running into a group and not having to target anything before.

Similarly, but possibly unrelated, if i try healing myself on WHM for example i have to manually target myself isntead of just using a heal spell while keeping my target on the boss.

Also it would be nice to have an option where i could manually use arms length, since it is also a tank mitigation cooldown :D

**Comment by awgil** [comment]
Outdated.
