### ISSUE TITLE
TOP

### ISSUE THREAD

**Issue by LANMAROU** [awgil/ffxiv_bossmod#190]
i was wondering does this plogon support all TOP phases?

**Comment by Ants1988** [comment]
No.

I believe this plugin only supports up to "Party Synergy".

Modules can't be written until the developer clears the fight and obtains required data to create a module.

**Comment by awgil** [comment]
TOP is hopefully going to be the next big module, we're gathering up a group for it atm.

**Comment by Peepolon12** [comment]
Not the right place probably, but you do such good work dude I'd like to know if there's any place you accept donos or something?
Square's absolute dismal when it comes to accessibility options so I have a hard time with severe colorblindness and Bossmod has been a saving grace.

Ty so much.

**Comment by awgil** [comment]
I've added kofi link to the github profile, here it is: https://ko-fi.com/andrewgilewsky

**Comment by awgil** [comment]
TOP is done now.
