### ISSUE TITLE
Will UCOB be added?

### ISSUE THREAD

**Issue by Theletha** [awgil/ffxiv_bossmod#191]
Will we see this added or is it too much work for old content? Since u cant run these unsynced they are very nice with bossmod on :)

**Comment by Niahmi** [comment]
Eventually, when the author gets around to it. [Commented here ](https://github.com/awgil/ffxiv_bossmod/issues/113#issuecomment-1482070486). Current big project upcoming is TOP, which the author is working on getting a group for.

**Comment by Theletha** [comment]
nice!
