### ISSUE TITLE
Plugin not working. Load error 

### ISSUE THREAD

**Issue by SneakyBelg** [awgil/ffxiv_bossmod#198]
![image](https://github.com/awgil/ffxiv_bossmod/assets/43534278/cff0b260-186c-4ea1-9259-24afbd4b5b21)

New version of dalamud does not work with the plugin. any chance we can get a quick fix for this?

**Comment by hidingfromu** [comment]
Same here

**Comment by jalkout** [comment]
It seems that the repositories aren't working

Can't find Boss mod when I search through all plugins anymore. used to work just fine tho.

**Comment by elleryb** [comment]
Edit the BossMod.json in your xivlauncher installed plugins/bossmod folder and look for where it says applicable version and change it to either 2023.11.09.0000.0000 or "any" and then it'll load if you don't wanna wait.

**Comment by princessoak** [comment]
> Edit the BossMod.json in your xivlauncher installed plugins/bossmod folder and look for where it says applicable version and change it to either 2023.11.09.0000.0000 or "any" and then it'll load if you don't wanna wait.

wait I did this but I think it might be really bugged. of course that's part of the risk I'm just saying this to warn people in case they kinda rely on it like I do :O

**Comment by hidingfromu** [comment]
It's weird that it's not even showing up in the repository though isn't it? Doesn't normally show it but say it's incompatible with the current version?

**Comment by Elementalzx14** [comment]
super glitchy, I wouldn't try the method above, displays mechanics all wrong

**Comment by awgil** [comment]
> Edit the BossMod.json in your xivlauncher installed plugins/bossmod folder and look for where it says applicable version and change it to either 2023.11.09.0000.0000 or "any" and then it'll load if you don't wanna wait.

This is a bad advice, the version check is there for a reason (reliance on network opcodes).

Anyway, this is now updated.

**Comment by princessoak** [comment]
> > Edit the BossMod.json in your xivlauncher installed plugins/bossmod folder and look for where it says applicable version and change it to either 2023.11.09.0000.0000 or "any" and then it'll load if you don't wanna wait.
> 
> This is a bad advice, the version check is there for a reason (reliance on network opcodes).
> 
> Anyway, this is now updated.

If I am a noob and did this cuz of desperation, is there anything I have to fix before updating it normally? :O

**Comment by awgil** [comment]
Just ensure you update to latest version.
