### ISSUE TITLE
Plugin crash when Ocean Fishing

### ISSUE THREAD

**Issue by SashaFFXIV** [awgil/ffxiv_bossmod#2]
![image](https://user-images.githubusercontent.com/55117631/154796800-c7d5f664-9105-4c87-9626-6a1af9d665b9.png)

Plugin crashes outright when you start Ocean Fishing. Probably due to it being a weird zone. Pretty sure it's Zone ID is 900 if I remember right.

**Comment by awgil** [comment]
Could you please send the log? It's should be in C:\Users\username\AppData\Roaming\XIVLauncher\dalamud.log, and should contain stack trace during crash

**Comment by SashaFFXIV** [comment]
[dalamud.log](https://github.com/awgil/ffxiv_bossmod/files/8102106/dalamud.log)

**Comment by awgil** [comment]
Should be fixed in new version.

**Comment by SashaFFXIV** [comment]
Not sure if the plugin has been updated with the fix but I'm still getting a plugin crash from Ocean Fishing.

![image](https://user-images.githubusercontent.com/55117631/155449067-56850b27-e787-4d6c-8926-57022e05ed5b.png)

[dalamud.log](https://github.com/awgil/ffxiv_bossmod/files/8129311/dalamud.log)

**Comment by awgil** [comment]
Tried again to fix it, please check whether it still crashes with new version...

**Comment by SashaFFXIV** [comment]
Hard for me to test more thoroughly cause my internet is dropping due to local flooding but I just hopped on the boat and the plugin didn't crash so we'll say it's fixed for now.
