### ISSUE TITLE
Doesn't actually work?

### ISSUE THREAD

**Issue by Violenze** [awgil/ffxiv_bossmod#200]
This has only worked once, and only with Titan EX. Why? I have tried with a ton of things and no radar or anything. Is there a discord that people can use for support or something?

**Comment by awgil** [comment]
Discord: https://discord.gg/Zzrcc8kmvy

I assume you didn't do any supported content - it is really mostly aimed at extremes/savages/ultimates type of things, and mostly for endwalker content. You can look at the sources (modules/) to see what exact modules are supported.
