### ISSUE TITLE
P12S Part 2 Pangen Error

### ISSUE THREAD

**Issue by Elementalzx14** [awgil/ffxiv_bossmod#201]
In the description you have for the 2+0 strat it mentions that all players who take first tower go north yet it displays a green circle on the tower to the south after a (short 2) takes first tower

**Comment by awgil** [comment]
This definitely used to work for me last time I checked - so I'll need a replay to investigate (/vbm -> replay recorder settings -> show recorder ui -> start)

**Comment by Elementalzx14** [comment]
I will try to get a recording of it when I can, I have not had luck getting (Short 2 again)

**Comment by awgil** [comment]
Outdated. No longer relevant content.
