### ISSUE TITLE
WHM Autorotation

### ISSUE THREAD

**Issue by elfsovereign** [awgil/ffxiv_bossmod#202]
Hey, this is an odd thing I've noticed using the mod - It seems that WHM has some amount of support with autorotation, I think I saw it's up to level 30. For some reason, and this may be one of those "eh it's two plugins not playing nice" kinda things but the autorotation window still pops up when I switch to WHM, but it doesn't work at 90. This would be a nothing muffin were it not that it then stops the spells it uses to activate the rotation from working at all, and I have to switch autorotations off entirely for the spells to work. I use Redirect to bounce my offensive spells off the tank and hit what they're hitting so I can respond to health loss quickly (a weird playstyle for sure), and maybe it's on redirect's side. In any event I figured I'd point out that it's trying to do the autorotation even though it doesn't know the spells. Just checked, WHM is the only one of the ARR classes to have this issue where the window appears despite being non-functional.

**Comment by awgil** [comment]
Outdated.
