### ISSUE TITLE
Killswitch autorotation

### ISSUE THREAD

**Issue by xKaori1** [awgil/ffxiv_bossmod#204]
Is there a way to add a kill switch to autorotation incase you don't want you burst to be used at a certain point you could press a certain key or make /macro.  For example adds phases during certain fights were you wouldn't want you use wanderers/coda/raging you could press something to stop and then when the boss comes back you can begin the autorotation.

**Comment by awgil** [comment]
The vbm's approach to this problem is cooldown plans. This is working fine for extremes/savages/ults/etc.

For 'casual' content (alliance raids etc) there is no way to do that currently, though I'd like to solve that somehow.
