### ISSUE TITLE
P10s - Plumes - Missing the middle danger zone

### ISSUE THREAD

**Issue by Theletha** [awgil/ffxiv_bossmod#205]
When the plumes starts there is no danger zone for the middle part

**Comment by CarnifexOptimus** [comment]
Does the middle even spawn its own danger zone? I think it might just be a visual circle. At least I cannot find a distinct plume middle AOE in my replay file.

**Comment by Theletha** [comment]
hm ye if u go into it u get a debuff or something dont remember what maybe it was a dmg over time debuff

**Comment by CarnifexOptimus** [comment]
You are right, the AOE makes bleed (just tested). But for some reason it does not appear as a voidzone when the spell starts. I assume it is made by a helper spawned at the start of the fight and activated by an ENVC (there is one right at the start and end of the spell). If I step into it the log says I got bleeding from noone.
I will see if there is another way to create this voidzone.

**Comment by CarnifexOptimus** [comment]
my pull request adds this missing voidzone, only tested in replay

**Comment by awgil** [comment]
Relevant PR is merged, should be fixed in latest version.
