### ISSUE TITLE
[request] make the map a windows so it can be moved to a secondary screen

### ISSUE THREAD

**Issue by Bloilo** [awgil/ffxiv_bossmod#206]
Hi!! so basically what the title says. Dalamud has the option to put plugins on other monitor and i think it would be useful to for some to put the map layout on another monitor.

**Comment by awgil** [comment]
^

I'll note that if you enable transparent background, window will be constrained to main game window - this is basically some limitation of dalamud (if you remove that constraint, you'll see ugly shit). So select one or the other - window with transparent background on second screen doesn't make much sense anyway.
