### ISSUE TITLE
Increase Icon Sizes a bit?

### ISSUE THREAD

**Issue by KhaozFrost** [awgil/ffxiv_bossmod#21]
possible to increase the waymark/compass as its scaled? everythings very tiny compared to the vanilla map so it can be difficult to see the little ant dots and such. I'm not asking for a massive increase but idk maybe the equiv of the vanilla map

**Comment by KhaozFrost** [comment]
yeah, It scales the arena itself up but the player dots/icons don't scale with it; they remain tiny

**Comment by awgil** [comment]
Fixed text scale (waymarks, cardinal names) in latest version. Player/enemy markers already respected arena scale from what I see though.

Could you please check after update whether something still seems to scale incorrectly? Also please attach screenshots if you still see any problems.
