### ISSUE TITLE
TEA: Arena border inaccurate

### ISSUE THREAD

**Issue by Flavescent** [awgil/ffxiv_bossmod#210]
In all phases of TEA, the arena border as displayed by Bossmod does not correspond to the actual arena border (the pink wall of death).

The actual arena border has a significantly smaller radius than the one displayed by Bossmod. This means that players who rely on Bossmod for positioning will often run into the wall and die.

Possibly as a result of this error, the position of the circular green position indicators displayed by Bossmod is also incorrect when the green circles are close to the wall. They overlap the actual arena border rather than touch it, also leading to deaths.

Thanks again for this very helpful mod!

**Comment by CarnifexOptimus** [comment]
do you have a replay where someone touches the wall? should be easy to fix

**Comment by awgil** [comment]
Fixed in v219
