### ISSUE TITLE
Thordan Unreal & Thaleia raid

### ISSUE THREAD

**Issue by Tarrent42** [awgil/ffxiv_bossmod#216]
Hello, I dont exactly know if its by Bossmod but it also doesnt work there like before.

In the game I dont see any aoe indicators, animations or castbar on targer or enemy list. also I dont see any enemies that are targetable, boss is just teleporting and dealing dmg while I have 100% knockback resist out of nowhere.  Bossmod showing nothing, game showing nothing except the characters and actual boss.

Im wondering if its by some error of bossmod or smthin else.

Thanku for response.

**Comment by awgil** [comment]
Thordan unreal is supposed to be working fine (checked last week), thaleia is not implemented yet.

I'll need the logs to investigate further, please see readme on instructions.

**Comment by Tarrent42** [comment]
Hey, I am so sorry, I figured it out and its not your plugin that makes the thing.

It was some setting in Penumbra.
