### ISSUE TITLE
Mount Ordeals Normal+EX issues

### ISSUE THREAD

**Issue by lyndistt** [awgil/ffxiv_bossmod#230]
Hi, 
Since 6.55 dropped, I saw that there has been some issues with mechanics not showing up properly on minimap on both Mount Ordeals normal and Extreme:
- Ordeal of Purgation doesn't show any safespot
- Flamespire Brand stack/flare indicators lingers long after mechanic resolves
- Limit cut does not show cleave indicator or who is receiving cleave

I have tried reinstalling the plugin completely and removing and readding repo, as well as running plugin alone.

Thank you in advance!

**Comment by CarnifexOptimus** [comment]
I don't think there is a module for Rubicante normal right now, only for extreme.
If it worked before and stopped working after 6.55 make sure it properly installed version .131. Only that version got the updated opcodes for 6.55

**Comment by awgil** [comment]
Yep, these symptoms look like an old version to me.

If you actually are running v.131+, please gather debug logs and replays and reopen.
