### ISSUE TITLE
P1S - Aetherflail during Last Shining Cells

### ISSUE THREAD

**Issue by Terrible-Legislation** [awgil/ffxiv_bossmod#24]
It shows the wrong safe tiles during the final phase of the fight.

**Comment by awgil** [comment]
Weird, didn't see that happen. Next time you do the fight, please record the log before pulling (General settings -> Dump world state events), and then attach it to the issue, so that I can investigate.

**Comment by abranon** [comment]
Can confirm this has happened to me a few times, I'll keep the option ticked and will provide the log if I ever come across it again!

**Comment by awgil** [comment]
Outdated.
