### ISSUE TITLE
MNK Shadow of the destroyer

### ISSUE THREAD

**Issue by Kensei-Seiryuu** [awgil/ffxiv_bossmod#242]
Arm of the destroyer works to trigger the AOE autorotation, but shadow of the destoryer does not. Is there a way to add in shadow of the destroyer to trigger the AOE rotation?

**Comment by Ants1988** [comment]
I think Arm of the Destroyer is coded as the trigger because it unlocks way earlier and SOTD is a trait upgrade.

It should be possible to make it trigger through either Arm or Shadow I think.

**Comment by Kensei-Seiryuu** [comment]
If an SOTD/ARM trigger becomes too tricky, could the trigger go to Four points, or even rock breaker?

**Comment by xanunderscore** [comment]
This will, among other issues with MNK, be fixed by https://github.com/awgil/ffxiv_bossmod/pull/249

Sorry for not catching it while working on the original version. Normally auto action placeholders work seamlessly with trait-upgraded actions, I'm not sure why shadow of the destroyer is a special case.

**Comment by Kensei-Seiryuu** [comment]
I figure this amongst other ones will be updated. GNB also has a glitch where during the aoe rotation it will stop completely unless a blast shell is used.

**Comment by Kensei-Seiryuu** [comment]
> This will, among other issues with MNK, be fixed by #249
> 
> Sorry for not catching it while working on the original version. Normally auto action placeholders work seamlessly with trait-upgraded actions, I'm not sure why shadow of the destroyer is a special case.

I figure this amongst other ones will be updated. GNB also has a glitch where during the aoe rotation it will stop completely unless a blast shell is used.

**Comment by Kensei-Seiryuu** [comment]
AoE rotation now activates on Shadow of the destroyer
