### ISSUE TITLE
could you add a few options

### ISSUE THREAD

**Issue by adambennett55** [awgil/ffxiv_bossmod#255]
could we get a / command to turn on / off AI
like

/vbm aion
/vbm aioff

and could we get a few options added to the boss mod ui under AI to turn Focus Target on and off and follow leader on and off

and could we get a couple / commands to turn these on and off as well like

/vbm fl on
/vbm fl off

and

/vbm ft on
/vbm ft off

and one last thing, could you give a way where other plugins can check to see if Boss Mod is currently Controlling Movement (aka dodging)

**Comment by McVaxius** [comment]
someone seems to have done some of that already in a pull request:

https://github.com/awgil/ffxiv_bossmod/pull/251

**Comment by adambennett55** [comment]
I also implemented most of this, minus the event. #256

**Comment by awgil** [comment]
Assumed to be fixed, since relevant PR is now merged.
