### ISSUE TITLE
[Request] Other Ultimate Fights

### ISSUE THREAD

**Issue by KhaozFrost** [awgil/ffxiv_bossmod#26]
I know it would be kinda tedious to go back and do old extremes, savages, etc at this time but i believe it'd be nice to atleast cover the ultimates (ucob/uwu/tea) first and foremost since they get progged alot. This plugin is by far the most amazing and fun to keep up with and currently replaces things like cactbot & trig for alot of stuff so I'm hoping those are high priority on the To-do list.
You're amazing. Keep it up and good job!

**Comment by awgil** [comment]
Old ultimates is definitely something I'd like to do. I need to actually do them myself for that (creating a module requires logs from plugin, video and understanding of mechanics to make sense of it). My static kinda had plans for doing all ultimates, but considering the constant problems we have I dunno when/whether we'll get there.

So, if you need a war and want to prog some ultimates, drop me a message :D

**Comment by Kumicoo** [comment]
Seconding this. UCOB would be epic.

**Comment by awgil** [comment]
As of v140, all ultimates have fully functional modules.
