### ISSUE TITLE
QOL Feature Request: Automatic Logging

### ISSUE THREAD

**Issue by LTS-FFXIV** [awgil/ffxiv_bossmod#273]
To help get logs for fights, an option to automatically start and stop at either in and out of combat or in the case of a trial/normal raid on barrier drop and duty complete.

**Comment by LTS-FFXIV** [comment]
Using Svc.DutyState as part of Ecommons would work to get dutycomplete

**Comment by awgil** [comment]
Outdated. This feature is now available.
