### ISSUE TITLE
What does the AI function do?

### ISSUE THREAD

**Issue by ZachieBlade** [awgil/ffxiv_bossmod#28]
Hi! Just curious about the AI function? I can't figure out what it's for exactly.
Thanks a lot!! I love your mod.

**Comment by awgil** [comment]
It's not particularly useful right now, it's just an experiment.

**Comment by StarkITA** [comment]
Hi, out of curiosity, is it still in the same state? I've toyed with it but still can't quite figure out its working and there's not much documentation about - if any
