### ISSUE TITLE
Request: P12S Classical Concepts Option.

### ISSUE THREAD

**Issue by EFHT** [awgil/ffxiv_bossmod#282]
It seems that currently Classical Concepts is using a sorting method from left to right with X, square, circle, and triangle shapes. For certain reasons, my team is currently using a sorting method with circle, X, triangle, and square shapes. Could you please consider adding an option to sort in this way?

**Comment by Ants1988** [comment]
Doesn't make sense to code in a completely new strategy that 1 person uses.

BPOG is the widely used and accepted strat hence why it's the one coded.

**Comment by talran** [comment]
I've been in a few numbers groups, it's easier to understand from zero.
But it's also like.... a braindead mechanic.

If you really need help with it just make a local repo for the project with CC order changed in BossMod/Modules/Endwalker/Savage/P12S2PallasAthena/ClassicalConcepts.cs

**Comment by EFHT** [comment]
> I've been in a few numbers groups, it's easier to understand from zero. But it's also like.... a braindead mechanic.
> 
> If you really need help with it just make a local repo for the project with CC order changed in BossMod/Modules/Endwalker/Savage/P12S2PallasAthena/ClassicalConcepts.cs

Thanks, I will try it.
