### ISSUE TITLE
Request: Option to turn off Generic AE Jousting

### ISSUE THREAD

**Issue by Herculezz55** [awgil/ffxiv_bossmod#290]
Alot of times when there is no Module and vbm detects an AE cast it will run your toons to the edge of the arena and hump the walls, or in worse cases right off the arena. would be nice to be able to turn this off and if its absolutely needed could be added in a module. P.S. obviously this is in AI Mode.

**Comment by awgil** [comment]
This should be fixed now, AI should never ever try pathing outside bounds. If this is still reproducible in some cases, I'll need details.

**Comment by Herculezz55** [comment]
This is where there is no module for a boss, so it has no arena bounds

**Comment by Herculezz55** [comment]
when this is the case it just runs forever until the cast is complete and alot of times runs out of the arena
