### ISSUE TITLE
Please add a module for "The Mothercrystal" (Hydaelyn)

### ISSUE THREAD

**Issue by Kitteh32842** [awgil/ffxiv_bossmod#299]
That trial was the main reason why I decided to download this addon, the "dawn mantle" mechanic always seems random so this would be super useful.

**Comment by LTS-FFXIV** [comment]
Do you have a log of this fight?

**Comment by McVaxius** [comment]
pass us some logs on disc

**Comment by CarnifexOptimus** [comment]
I can make one, i got a replay

**Comment by CarnifexOptimus** [comment]
#301
i hope everything works, only tested it once

**Comment by awgil** [comment]
Module is available in v140.
