### ISSUE TITLE
Auto-Rotation keystroke visibility

### ISSUE THREAD

**Issue by FloBoBre** [awgil/ffxiv_bossmod#318]
It would be great if the Auto-Rotation (when set to sticky key) mimics real keystrokes on the hotkey bar on the right skills. That would probably require an additional setup step but it would be totally worth it for those who really cant be arsed explaining to friends why the icons on the hotkeybar dont light up!

**Comment by awgil** [comment]
No plans to implement. VBM doesn't touch hotbars and doesn't send keystrokes, so that would need to be a bespoke system. I don't really care about streaming (or hiding vbm while streaming), so not really interested in doing the work.
