### ISSUE TITLE
Thaliea

### ISSUE THREAD

**Issue by Kensei-Seiryuu** [awgil/ffxiv_bossmod#319]
I saw that Thaliea was merged in the pull request, but the module is not working. Is it still WiP?

**Comment by CarnifexOptimus** [comment]
it wasn't merged, LTS deleted it because he wants it to be exclusive to his new project

**Comment by Kensei-Seiryuu** [comment]
> it wasn't merged, LTS deleted it because he wants it to be exclusive to his new project

Is that the bossmod reborn?

**Comment by CarnifexOptimus** [comment]
yes

**Comment by CarnifexOptimus** [comment]
Thaleia is now implemented in this version of bossmod, give it a try

**Comment by awgil** [comment]
Outdated. This is available now.
