### ISSUE TITLE
Not showing up in dalamud

### ISSUE THREAD

**Issue by lanckim5** [awgil/ffxiv_bossmod#323]
Hello, I followed all instructions as written but bossmod is not showing up whenever I go to search for it in dalamud. I can see the other plugins in the repository except bossmod for some reason. Have had this issue for a week and have yet to find an answer. Here's what my custom repository setting looks like and my plugin search.

![Screenshot 2024-04-02 144222](https://github.com/awgil/ffxiv_bossmod/assets/165833697/d8d46bbd-0a07-4198-9a06-03f81b633e1b)
![Screenshot 2024-04-02 144255](https://github.com/awgil/ffxiv_bossmod/assets/165833697/a22537cd-6c60-4996-a507-d5fb39439203)

**Comment by Ants1988** [comment]
https://puni.sh/api/repository/veyn is the correct repo

**Comment by lanckim5** [comment]
> https://puni.sh/api/repository/veyn is the correct repo

When I copy and paste this repo it automatically changes to the repo seen above. Even when I type it out myself it does the same.

**Comment by Ants1988** [comment]
remove the love.puni.sh one and then add the one I posted

**Comment by lanckim5** [comment]
> remove the love.puni.sh one and then add the one I posted

That worked, thanks!
