### ISSUE TITLE
Color choice for safe zones and others

### ISSUE THREAD

**Issue by EricClerfayt** [awgil/ffxiv_bossmod#327]
Hi, Wondered if it would be possible to modify the color for safe zones and stuffs, I'm doing Criterions right now and i struggle to see the difference between safe zones and AoEs in the middle of the fight (Somewhat of a little daltonism)
Thx

**Comment by CarnifexOptimus** [comment]
I think someone was working on making colors selectable (@sourpuh on discord), but I am not sure when its ready.

**Comment by awgil** [comment]
Fixed (finally!) in v241.
