### ISSUE TITLE
DSR Playstation Strat

### ISSUE THREAD

**Issue by KhaozFrost** [awgil/ffxiv_bossmod#33]
People seem to swap up the postions alot so wondering if you could add in options for the ability to customize those spots
have the 8 spots
![image](https://user-images.githubusercontent.com/15788954/180107834-1a50d114-4c15-43b7-816f-6fa488d69f99.png)
Reference Example
[1] [2] [3]
[4]      [5]
[6] [7] [8]
with selector below Such as
1 = □[✓] O △ ╳ | T H[✓] D
2 = □ O △ ╳ | T H D
3 = □ O △ ╳ | T H D
4 = □ O △ ╳ | T H D
5 = □ O △ ╳ | T H D
6 = □ O △ ╳ | T H D
7 = □ O △ ╳ | T H D
8 = □ O △ ╳ | T H D
that way regardless of how the party does it; when tthey get shown in the map; nobody will be scuffing the mechanic up looking at the plugin.
Also by default what is the normal setup the plugin uses for this mechanic?

**Comment by awgil** [comment]
Normal setup is color matching to waymarks. I'll think how it can be customized.

**Comment by awgil** [comment]
Outdated. This option is now long supported.
