### ISSUE TITLE
Request: more options for DRG and RPR in CD planner.

### ISSUE THREAD

**Issue by averydankmemer** [awgil/ffxiv_bossmod#331]
Would like battle litany, dragon sight, lance charge, and maybe stardiver in the cdplanner for situations where you have to hold raid buffs like in some ultimates. Also an option to not use the disembowel and chaos thrust combo would be nice. As for reaper just one additional option under the gauge category where it doesnt use death design but instead uses the normal combo. for example in DSR at the end of P2 thordan, force a slice instead of DD

**Comment by awgil** [comment]
Outdated. Class modules are improved when someone does that.
