### ISSUE TITLE
void cast extreme fake anti knockback issue

### ISSUE THREAD

**Issue by Dedoooo** [awgil/ffxiv_bossmod#338]
minor issue but would be nice to identify such things that are resistant to anti kb

In case there's more clarification needed: When certain attacks that knock you back are immune to Inner Strength, Surecast and Arm's Length they hide the indicator for the knockback position, which I find as a minor annoyance and misleading, if it would be possible to have a workaround for these attacks to ignore the effect of anti knockback

**Comment by CarnifexOptimus** [comment]
the knockback component has a bool for immune to knockback.
if you find any knockbacks where the flag for immune to antiknockbacks is missing, please list them

**Comment by awgil** [comment]
Outdated. No info is provided, and this is no longer relevant content.
