### ISSUE TITLE
Modules not resetting if boss resets

### ISSUE THREAD

**Issue by CarnifexOptimus** [awgil/ffxiv_bossmod#341]
Modules are not resetting if boss gets reset by running out of its range. Eg. A/S Ranks and FATE bosses.
This can lead to problems if the boss is doing an attack right after being pulled (eg. S Rank Tarchia) or if multiple modules are suddenly active at the same time.
Adding a raw update check for boss is in combat unloads the module entirely and does not just reset it, so you need to run out of range and back for it to get loaded again.

**Comment by awgil** [comment]
Fixed recently.
