### ISSUE TITLE
videos

### ISSUE THREAD

**Issue by LANMAROU** [awgil/ffxiv_bossmod#346]
is there any way to see how the module would look like or be in a certain fight or phase? or should i reach p5 in top to figure it out by myself?

**Comment by LANMAROU** [comment]
also the discord link says unable to join, is there any other link?

**Comment by Ants1988** [comment]
You'll need to reach the phase yourself to see how it looks.

**Comment by CarnifexOptimus** [comment]
you could try to get a replay file, they are shareable. i don't have any TOP replays though

**Comment by LANMAROU** [comment]
> you could try to get a replay file, they are shareable. i don't have any TOP replays though

from where

**Comment by CarnifexOptimus** [comment]
from other players who use this plugin obviously, you will have to ask around

**Comment by LANMAROU** [comment]
well then i have 1 quastion only, at sigma in TOP will it show me what tower to take or will it shows green on all towers?

**Comment by awgil** [comment]
VBM does not provide a way to get the video without actually doing the fight (or watching ARR recording)
