### ISSUE TITLE
Boss module disappears/doesn't show up in instances

### ISSUE THREAD

**Issue by sliqhtlymad** [awgil/ffxiv_bossmod#35]
I wanted to test the mod in Sastasha, and it showed up fine at the beginning. But as soon as I transitioned from "Sastasha Seagrot" to "The Cattery" - the window with the map disappeared completely. In other instances, it doesn't show up at all. Did I press a wrong button or is this a bug somehow? Thanks!

**Comment by GypsyFirebrand** [comment]
Hubby and I are having the same problem. I installed yesterday and today did a EW Hunt train and OMG loved the help with getting away from mechs! but then did Void Ark and a few other duties and it never showed up :( Looks as if its working for others so wondering what we may have done wrong? Please Help 
Thank you Gypsy and Tass :)

**Comment by Niahmie** [comment]
Not all content is supported at the moment. It has to be added instance by instance, you're not doing anything wrong and it's not a bug. The plugin will only show the window in supported content, some dungeons are supported, some aren't.

**Comment by awgil** [comment]
This is mostly useful for high-end content, other things are added slowly.
