### ISSUE TITLE
BLM, SMN, PLD Auto rotations fail to load on job change

### ISSUE THREAD

**Issue by ShadowArc147** [awgil/ffxiv_bossmod#354]
SAM, RPR, DRG, MNK, WAR and GNB all seem to load ok. 

Show in game UI toggle shows loaded module but BLM, SMN, PLD fail to do so. Target dummy rotation check fails too.

**Comment by Ants1988** [comment]
BLM SMN and PLD are only supported up to like level 30.

They will not load past that level.

**Comment by awgil** [comment]
Outdated.
