### ISSUE TITLE
Can‘t open UI

### ISSUE THREAD

**Issue by ImNoobezio** [awgil/ffxiv_bossmod#356]
I follow the install step 'add https://puni.sh/api/repository/veyn' and install bossmod. but i cant open config UI and cant use in some quests.
here is the error:
        | ERR | Exception during raise of "Void OpenConfigUI()"
	System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
	   at BossMod.ModuleViewer.Classify(Info module) in /home/runner/work/ffxiv_bossmod/ffxiv_bossmod/BossMod/Config/ModuleViewer.cs:line 251
	   at BossMod.ModuleViewer..ctor() in /home/runner/work/ffxiv_bossmod/ffxiv_bossmod/BossMod/Config/ModuleViewer.cs:line 77
	   at BossMod.ConfigUI..ctor(ConfigRoot config, WorldState ws) in /home/runner/work/ffxiv_bossmod/ffxiv_bossmod/BossMod/Config/ConfigUI.cs:line 20
	   at BossMod.Plugin.OpenConfigUI() in /home/runner/work/ffxiv_bossmod/ffxiv_bossmod/BossMod/Framework/Plugin.cs:line 136
	   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act)
![321](https://github.com/awgil/ffxiv_bossmod/assets/169599356/532ab776-051a-43de-9e21-9ba0da64ac08)

but the bossmod works in some sepcific quest like 'A Finale Most Formidable' and boss in ‘the Praetorium’
![2133](https://github.com/awgil/ffxiv_bossmod/assets/169599356/c1562324-b2bc-48db-97d4-df8f8a225e56)

I don't know this issue happened because I'm a CN platform player or i install bossmod in a wrong way.
I wish some good guys could help me to fix this issue, Thx.

**Comment by CarnifexOptimus** [comment]
you need to use the chinese fork https://github.com/44451516/ffxiv_bossmod

**Comment by ImNoobezio** [comment]
> you need to use the chinese fork https://github.com/44451516/ffxiv_bossmod

thank you, you help me a lot

**Comment by CarnifexOptimus** [comment]
No problem. This problem comes up a lot, I am not sure why the UI does not work on the chinese version. Not sure if it can be fixed directly or is a problem resulting from the chinese dalamud version.

**Comment by Artanis55** [comment]
> No problem. This problem comes up a lot, I am not sure why the UI does not work on the chinese version. Not sure if it can be fixed directly or is a problem resulting from the chinese dalamud version.

Chinese users may encounter this issue. Could we include the solution in the readme.md to prevent more Chinese users from being unable to use the product or submitting unnecessary issues?Thank you very much for your understanding and assistance.

**Comment by awgil** [comment]
Outdated.

**Comment by moefive** [comment]
This fork has been deleted, the user also been deactivated.
