### ISSUE TITLE
Installation of Plugin Stuck.

### ISSUE THREAD

**Issue by AegisCat** [awgil/ffxiv_bossmod#36]
So I am currently trying to install the plugin and it's currently stuck trying to install and has been for the past 15 minutes. Is this normal and the plugin just has a lot to download or is it actually frozen? Tried restarting the download a couple times which lead it to corrupt and then it just stays installing for a while when I clean it and reinstall.
![Screenshot 2022-08-11 225633](https://user-images.githubusercontent.com/45326071/184293392-dd062cad-70bf-4580-ba47-40bafff6d526.png)

**Comment by awgil** [comment]
No idea, looks like some problem with dalamud rather than plugin. If this continues to happen after last update, please reopen the issue and attach some logs to investigate.
