### ISSUE TITLE
Healer Self Target

### ISSUE THREAD

**Issue by TokTikToe** [awgil/ffxiv_bossmod#371]
Not sure if its just me but when i have Boss Mod enabled it stops targeted healing spells (e.g Cure, Cure II ) from being cast automatically on self while an enemy is targeted, it acts the same was as a offensive spell would i had no target. tested a couple times that function works when Boss Mod is disabled but then immediately stops when i enable it again. The plug in is up to date as far as i can tell. Dalamud Plugins is telling me its v0.0.0.164 

oh and i am only using the "Radar" function of the mod

**Comment by cptn-cosmo** [comment]
#186

**Comment by awgil** [comment]
Outdated, fixed now.
