### ISSUE TITLE
UI doesn't popup in dungeons/trials after 6.2 update

### ISSUE THREAD

**Issue by CommyPeter** [awgil/ffxiv_bossmod#39]
The plugin loads fine and I can even modify the settings in game. I can also open up the demo view to see the changes I'm making but it seems when I go into a trial or dungeon the plugin doesn't show the radar UI like it did before 6.2. There is nothing in the Dalamud log as well. I've tested this on my desktop and my laptop just to be sure it wasn't a config or something and on both the UI never pops up.

**Comment by InvictusAternum** [comment]
I'm hoping this will be regularly updated as I feel it is a real handy mod!

**Comment by awgil** [comment]
Yeah, old content is mostly not supported for now.
