### ISSUE TITLE
Reset Display Position

### ISSUE THREAD

**Issue by TheFallenZX** [awgil/ffxiv_bossmod#394]
Needs a way to reset position on screen.
Due to playing on a laptop, and using a monitor at times, i move the window from time to time.

How ever, it tends to get stuck off the screens when resolutions change.
There doesn't seem to be a way to reset the location of the display.

I have tried resetting the pulgin, and uninstalling and re-installing the plugini. 
It still does not display on my screen. even with "Config mode" turned on.

![image](https://github.com/user-attachments/assets/7f62ee4a-104a-485e-b40b-e165e9036725)

**Comment by awgil** [comment]
This is more of a dalamud request. If it's a one-time thing, you can edit saved window positions in the ini.
