### ISSUE TITLE
Boss mod AI max distance to target reset every duty pop

### ISSUE THREAD

**Issue by yudistiraen** [awgil/ffxiv_bossmod#398]
i have this issue from recent update that make boss mod AI max distance to target will reset every duty pop, dats kinda annoying that i need to adjust it again

**Comment by CarnifexOptimus** [comment]
This is an AutoDuty problem, ask them for support

**Comment by adambennett55** [comment]
Not only is this Caused by AutoDuty, But it is also not part of this BossMod, Anyways check the config tab, there is an option to turn off Manage BossMod AI Settings

**Comment by yudistiraen** [comment]
ow, okay i tought this is from bmr sorry and thankyou
