### ISSUE TITLE
MCH Rotation bug

### ISSUE THREAD

**Issue by azarathie** [awgil/ffxiv_bossmod#399]
Machinist rotation been working pretty well in making things stay on cooldown, however it's not using wildfire on the opener. If you forget to use it manually, it'll automatically use it in the 1min-ish mark. 

Sometimes it's also overcapping the battery gauge and using Reassemble in the 1-2-3 combo.

**Comment by Nepuru999** [comment]
Hey are you just testing it for them? or is the mch rotation out? just curious :)

**Comment by xanunderscore** [comment]
try with latest version, and get a replay if both issues continue happening so i can debug

**Comment by azarathie** [comment]
It improved a lot, thanks
