### ISSUE TITLE
P1S Shining Cells Aetherflail mechanic does not display Out

### ISSUE THREAD

**Issue by SashaFFXIV** [awgil/ffxiv_bossmod#4]
Piggybacking from #3 and making a new issue. For whatever reason the Boss Module does not display the Out mechanic in-game. From what I can tell it displays In just fine, it's just Out.

![image](https://user-images.githubusercontent.com/55117631/155269567-97d4a5ac-1978-43e2-a083-100d97caa5e9.png)

EDIT: I also just had it fail to display an In on the second Shining Cell Aetherflail but I lost the screenshot before I could copy it here.

**Comment by awgil** [comment]
Fixed. This is one mechanic I've broken at least 4 times now :D
