### ISSUE TITLE
prevent movement while casting not working

### ISSUE THREAD

**Issue by neongrey** [awgil/ffxiv_bossmod#40]
Hey, I turned on 'prevent movement while casting' to help practice my slidecasts. it worked in 6.1 but it doesnt seem to be working in 6.2 anymore.

eta: oh, also even before while it would stop you from moving during your cast, if you started a cast again while moving it wouldnt stop you; this is ok behaviour but not what i expected

really appreciate the tool btw, i have a *lot* of trouble visually tracking things in motion, especially brightly coloured things (and boy howdy is this tier gonna push that even farther, can't see bough of attis for heck) so it's been a huge help for me in increasing precision last tier.

**Comment by awgil** [comment]
Will think if it's possible to restore this feature while autorotation is disabled.

**Comment by awgil** [comment]
Outdated. No longer relevant.
