### ISSUE TITLE
Auto Rotations

### ISSUE THREAD

**Issue by niku2561** [awgil/ffxiv_bossmod#416]
I have been reading a lot about some auto rotation updates however i cant seam to find them or get them to work in the old overlay there way a checkbox to turn on autoroation for the classes you wanted  but i cant find that option now?

a qick rundown of where to find the new option for it would be great! <3

**Comment by NightXIV** [comment]
https://github.com/awgil/ffxiv_bossmod/wiki/Presets

**Comment by awgil** [comment]
Wiki link posted above should explain everything.
