### ISSUE TITLE
Nald'Thal cones don't go away when resolved

### ISSUE THREAD

**Issue by neongrey** [awgil/ffxiv_bossmod#42]
The cone markers in the last section of the nald'thal fight aren't going away for me once the mechanic resolves.

**Comment by neongrey** [comment]
also i was farming hydaelyn ex last night and her first aoe isnt clearing either

**Comment by neongrey** [comment]
this appears resolved with the version bump! Thanks!! <3

**Comment by awgil** [comment]
Yeah hydaelyn i would expect so, re. nald'thal - i think there's still some issue, i've seen it long ago but didn't get around to fixing it...
