### ISSUE TITLE
Worqor Zormor

### ISSUE THREAD

**Issue by fayness** [awgil/ffxiv_bossmod#422]
Fails the mechanic from 2nd boss where you have to attack the crystal on the player and not the boss.

**Comment by awgil** [comment]
This is weird, the priorities for adds are set correctly as far as i can see. What exactly are you doing? (autoduty? manually enabling ai?)

**Comment by awgil** [comment]
Did not get the response, can't reproduce, assuming it's a non issue. Please reopen with details if still reproducible somehow.
