### ISSUE TITLE
M1S - Mouser 1 - Target not always applied  

### ISSUE THREAD

**Issue by Theletha** [awgil/ffxiv_bossmod#425]
The attack where the boss attacks a player is not always shown its like the plugin doesn't register who gets the attack and nothing is displayed for that attack where it normally would (Yellow color on player and danger zones). It happens sporadically but fairly often. 

The exact attack is this one: https://youtu.be/9UB5x8JzAiQ?t=345

**Comment by awgil** [comment]
Please record a replay showcasing this issue and send it for me to investigate.

**Comment by Theletha** [comment]
> Please record a replay showcasing this issue and send it for me to investigate.

Here is a compilation i made of 3-5 clips. it seems to be mostly Jump 2 but also one was Jump 3. 

https://www.youtube.com/watch?v=VinQ6-JIIkw

**Comment by awgil** [comment]
I meant vbm replay (see main page, 'getting help' section), I can't really investigate this based on video alone...

**Comment by Theletha** [comment]
> I meant vbm replay (see main page, 'getting help' section), I can't really investigate this based on video alone...

i see, ill do it next time i enter the duty

**Comment by awgil** [comment]
Finally reproduced for me yesterday, fixed in v245.
