### ISSUE TITLE
Endsinger; planets.

### ISSUE THREAD

**Issue by Nyssiar** [awgil/ffxiv_bossmod#43]
Just tried to do Endsinger a few minutes ago, noticed that while most of the AoE's are still shown, the knockback prediction and planet aoe's for orange are now no longer showing at all.

**Comment by Nyssiar** [comment]
I forgot, 6 Heads also arn't being shown. However all the other aoe's are working fine like before.

**Comment by awgil** [comment]
Most likely was broken after patch. Please reopen if it's still relevant.
