### ISSUE TITLE
installed incorrect since 0.0.0.209

### ISSUE THREAD

**Issue by trulynb** [awgil/ffxiv_bossmod#434]
![image](https://github.com/user-attachments/assets/e75c519a-c6ea-49cd-b9fa-b027e09bc207)
Tried deleting the bossmod folder under pluginconfigs, but that didn't work.

**Comment by awgil** [comment]
What is in your dalamud.log? There's probably some exception there that says what's wrong. See home page ('getting help' section) for details on how to find it.

**Comment by trulynb** [comment]
[dalamud.log](https://github.com/user-attachments/files/16721384/dalamud.log)
I don't see anything unusual here.

**Comment by awgil** [comment]
Is this still an issue?

**Comment by trulynb** [comment]
> Is this still an issue?

problem solved. after dalamud update itself when 7.05 hotfix002.
