### ISSUE TITLE
Vanguard bugs

### ISSUE THREAD

**Issue by Jaksuhn** [awgil/ffxiv_bossmod#448]
Boss 2

- AI movement during the spin attack is kind of janky. Ends up freaking out when it falls behind the upcoming spin spots due to dodging the other aoes going off during the time
- AI when handling acceleration bomb correctly stops, but it stops at like 3 seconds left, and refuses to dodge the line aoes that it will inevitably be hit by (that it does have time to dodge then stop)

Boss 3 (Phase 2)

Towards the end when it does the line aoe + half room cleave, the line aoe portion isn't drawn

**Comment by awgil** [comment]
* B2 acceleration bomb 'forbid movement' aihint is reduced to 0.5s
* B3 was fixed some time ago

Can you send a replay that showcases janky movement on spins?

**Comment by Jaksuhn** [comment]
> B3 was fixed some time ago

After the posting of this issue? I was on latest at the time of posting.

Sent a replay on discord

**Comment by awgil** [comment]
> After the posting of this issue? I was on latest at the time of posting.
yeah, there was some other issue about the same thing

**Comment by Jaksuhn** [comment]
resolved in one of the recent commits
