### ISSUE TITLE
Huge Thanks first

### ISSUE THREAD

**Issue by Ashura1996** [awgil/ffxiv_bossmod#45]
First at all i want to Thank u for This wonderfull Plugin! i mean i saw something like that in the Youtube drama but i wasnt thinking that this will acutally work , i mean sure its still Alpha Phase but im sure this one will go wild :) , if u need any help with testing out stuff like other boss fights form Realm reborn , Heavnsward Stormblood , Shadowbringers and Endwalker , just let me know im sure this will also help for a lot of Ulitmate sutff , like they did in the Videos on reddit and Youtube :)

**Comment by Dubsys** [comment]
This is not how you use github

**Comment by awgil** [comment]
Closing, since it's not an issue.
