### ISSUE TITLE
(P5s) the ruby glow after 1st devour where front is safe shows back as safe

### ISSUE THREAD

**Issue by Dedoooo** [awgil/ffxiv_bossmod#46]
seen it happen twice. is there a better way to show you this issue?

**Comment by awgil** [comment]
Which ruby glow is that? After devour - so you mean 4th, the one where you have to recolor 2 stones to poison? It's supposed to show side with 3 stones as dangerous.

**Comment by awgil** [comment]
Reproduced on reclear today, will fix soon...
