### ISSUE TITLE
Un5Thordan - distance for Dimensional Collapse too low

### ISSUE THREAD

**Issue by armine021** [awgil/ffxiv_bossmod#472]
When Dimensional Collapse goes out, an initial black circle is on the floor and movement is accurate to its border, but the circle expands over time and you will stand in bad if you don't manually move further.

Not sure what the correct distance is as I don't know how to modify and test myself. Believe the issue is here:

BossMod/Modules/Endwalker/Unreal/Un5Thordan/Intermission3.cs
`class DimensionalCollapse(BossModule module) : Components.LocationTargetedAOEs(module, ActionID.MakeSpell(AID.DimensionalCollapseAOE), 9);`

**Comment by CarnifexOptimus** [comment]
how can you even play unreal thordan right now?
