### ISSUE TITLE
 About EnvironmentControl

### ISSUE THREAD

**Issue by tssailzz8** [awgil/ffxiv_bossmod#5]
how can i find the EnvironmentControl opcode

**Comment by awgil** [comment]
Simplest way I've found is to enable network dump, go to P1S and wait for intemperance - there should be a sequence of 24+ messages with same opcode when cubes appear - these are envcontrols. I guess similar could be done in normal, but there are fewer cubes and so fewer messages.

**Comment by tssailzz8** [comment]
What software do you use to

**Comment by tssailzz8** [comment]
What software did you use to find the package

**Comment by awgil** [comment]
Package? What do you mean?

**Comment by tssailzz8** [comment]
Network package

**Comment by awgil** [comment]
Closing this, as I don't really understand what kind of information I can provide here...
