### ISSUE TITLE
List with all available instances

### ISSUE THREAD

**Issue by Kumicoo** [awgil/ffxiv_bossmod#50]
Hey there. is there a list with all available instances?

Encounter specific settings are not everything.

TY

**Comment by awgil** [comment]
Currently not. Easiest way would be to look at the code (just see what there is in Modules directory, it's structure should be self-explanatory). But yeah, would be a good idea to have some automatically generated list somewhere...

**Comment by awgil** [comment]
Outdated. This list is now part of the plugin.
