### ISSUE TITLE
Cone of vision on minimap

### ISSUE THREAD

**Issue by Spanglish1337** [awgil/ffxiv_bossmod#51]
![image](https://user-images.githubusercontent.com/89648547/189465075-75812f65-03de-488e-b30d-e0ec35a24b4d.png)

Is there a way to have cone of the vision of your camera, where your camera is looking at, just like in the regular minimap?

**Comment by awgil** [comment]
Not now. I remember seeing such a request already, just never got around to implementing it.

Technically it's really simple, I just have no idea how to make it both visible enough and not interfering with aoes and stuff - so specifically, I need to tweak (a) cone length, (b) cone border color/opacity, (c) cone interior color/opacity.

**Comment by awgil** [comment]
Outdated. No plans to implement, since there has not been much interest in this feature.
