### ISSUE TITLE
Game freeze in Mt. Gulg

### ISSUE THREAD

**Issue by cabbscripts** [awgil/ffxiv_bossmod#516]
Approaching the zone transition after the first wall miniboss causes a hard freeze. No crash log created due to having to close the game through task manager. Tested by queueing solo unsync:

Kill first boss -> kill wall miniboss before zone transition -> game freeze

**Comment by Putrefalcis** [comment]
Can confirm. When engaging the pack of 4 mobs at this point on the map, the game freezes. Happens every time.
![Screenshot 2024-10-02 052141](https://github.com/user-attachments/assets/251b8e9a-0f38-4114-a076-117c2b6cd94f)

**Comment by awgil** [comment]
Should be fixed in v251.
