### ISSUE TITLE
How do I know if it's working?

### ISSUE THREAD

**Issue by Soggim** [awgil/ffxiv_bossmod#52]
I followed the setup instructions and Dalamud's setup, but I don't believe the plugin is working as it should. I don't get a window showing bosses' attack patterns nor do any of the other features work. The only thing I can think of is that I set it up wrong, but I don't know where or how? I followed the instructions below.

**Comment by Gitnuhin** [comment]
right same here, I have no idea what I've done wrong or know how to fix it whatsoever, since you posted this 2 weeks ago I'm sure there no help incoming for the issue

**Comment by Ants1988** [comment]
You should see something like this when you're infront of a supported boss.

https://i.imgur.com/bYc7t0m.png

**Comment by awgil** [comment]
Closing since answer is provided.
