### ISSUE TITLE
Hangs on installing/updating plugin

### ISSUE THREAD

**Issue by happilysleeping** [awgil/ffxiv_bossmod#54]
I've noticed that any time i try to install or update the plugin, it hangs on the little pop up window saying Installing Plugin/Updating Plugin. I think it resolves with a restart, but doesn't go away otherwise. Not sure what it might be, so figured I'd report.

**Comment by Cyrox94** [comment]
I tried installing for the first time and it just got stuck on "installing" after a restart i got a dalamund error that a plugin was blocking the plugin installer and wouldnt go away until I manually delted the boss mod file from the %appdata% folder.

**Comment by awgil** [comment]
Seems like a dalamud problem, no idea what's wrong here.
