### ISSUE TITLE
About waymarks color

### ISSUE THREAD

**Issue by Ygrtry** [awgil/ffxiv_bossmod#55]
Hello sir
Color of waymarks displayed on my radar.
Different from the color of the venue marker.
E.g:
A.1 Red
B.2 Yellow
C.3 Blue
D.4 Purple
Is there any way to change this?
Or my settings are not correct?
Still thank you very much for your creation.

**Comment by awgil** [comment]
Waymark colors on the radar are currently hardcoded. If you want to propose different colors, feel free to reopen issue and write them (any format you like, I need R/G/B values) - if I like them more than what there currently is, I'll update :)

**Comment by MinakataEnteh** [comment]
I too was wondering about the color difference, so let me suggest a color.
How about the following R/G/B values?
A(1):#E54E96
B(2):#C6A211
C(3):#309FE2
D(4):#7A56BC

Please consider.

**Comment by awgil** [comment]
Fixed in v82, thanks!
