### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by zhanghuatao** [awgil/ffxiv_bossmod#552]
The FF14 national server Weiyue 
![微信截图_20241203194247](https://github.com/user-attachments/assets/49ce80ed-1a26-447f-8bbe-6a0c931c3c41)
plug-in keeps failing to load.
![image](https://github.com/user-attachments/assets/a2826aeb-8571-4994-a995-77459fe77c2a)

**Comment by Ants1988** [comment]
You need to use the CN version, this is the version for Non-CN clients.

**Comment by awgil** [comment]
Yeah, that is right - I can't really support CN (don't have access), but there is some fork afaik...
