### ISSUE TITLE
Radar not showing up in any instance 

### ISSUE THREAD

**Issue by minoslune** [awgil/ffxiv_bossmod#65]
Hello,

Im having some trouble with the add on, up until a few days ago it seems like it was working fine but now when I enter an instance the radar remains hidden and if I force it to appear with the "show boss module demo out of instance" option it does appear inside the instance but its just that, the demo and it wont really show anything but my character arrow moving inside of it. Here are the logs, I hope someone can help me with this, I went to a abyssos 8 normal before uploading the log so that the situation where the radar doesnt show up would happen again.
[dalamud.log](https://github.com/awgil/ffxiv_bossmod/files/9856491/dalamud.log)
Thank you.

**Comment by minoslune** [comment]
When I force it to show the demo out of instances it looks like this... 
![image](https://user-images.githubusercontent.com/7550404/197657958-aed32ae9-d4bb-4480-898d-e33e381fa175.png)
and whenever im inside of an instance and I force show it it looks like this: 
![image](https://user-images.githubusercontent.com/7550404/197658258-5cca1c06-ed7f-4663-8ae3-89e2dc6ddcc8.png)
if shows me moving around but the demo "me" and demo aoe still shows there, none of the actual mechanics show there tho

**Comment by minoslune** [comment]
and these are my settings if it helps anything... 
![image](https://user-images.githubusercontent.com/7550404/197659356-c8e61030-4349-4308-8cb2-4386571ffd05.png)

**Comment by minoslune** [comment]
Ok so I read the stuff about the logs that I should post lol, sorry about not doing it sooner, I entered an abyssos 8th floor normal so I could recreate the situation and here are the logs:
[dalamud.log](https://github.com/awgil/ffxiv_bossmod/files/9856472/dalamud.log)

**Comment by awgil** [comment]
There is no support for EW normal raids. Try some savage/extreme/unreal and it should work.

**Comment by minoslune** [comment]
omg, im such an idiot, thanks for the help Awgil
