### ISSUE TITLE
Autorotation

### ISSUE THREAD

**Issue by KullaniciAdiAlinmis** [awgil/ffxiv_bossmod#69]
I am dumb and I just cannot figure out how to use it. Help :(

**Comment by StaticSadness** [comment]
it only works for whm

**Comment by Vinz7** [comment]
Hello Here !!
Thank you for this great module.
Currently i can only use Bard and Warrior, for the other classes the module seems to not load.
Do i have to do something, or is it normal atm?

**Comment by Ants1988** [comment]
Normal.

Only warrior works well,  Bard is semi well.

Rest don't work.

**Comment by awgil** [comment]
Outdated
