### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by pallmaaa** [awgil/ffxiv_bossmod#7]
Hey, for plebs like me, would you mind adding a tutorial on how to install?

Dalamud says download failed whenever I try to add the repo, as if its not detecting it or something. Am I just dumb?

**Comment by awgil** [comment]
1. esc -> dalamud settings -> experimental -> custom plugin repositories, add https://raw.githubusercontent.com/awgil/ffxiv_plugin_distribution/master/pluginmaster.json
2. esc -> dalamud plugins -> all plugins -> find "Boss Mod" and install
3. settings are accessible either via esc menu or /vbm console command
