### ISSUE TITLE
Plugin fails to install/load

### ISSUE THREAD

**Issue by amki** [awgil/ffxiv_bossmod#71]
After 6.28 update the plugin fails to load even if I manually delete the configuration and reinstall it.

The dll is being extracted to the correct folder but it looks like it can't be loaded.

[log.txt](https://github.com/awgil/ffxiv_bossmod/files/9939532/log.txt)

**Comment by awgil** [comment]
Need more details - according to the log, plugin was loaded. But the log seems to be edited?..
