### ISSUE TITLE
Multi-Monitor Issue

### ISSUE THREAD

**Issue by zfrxxy** [awgil/ffxiv_bossmod#72]
When using the Multi-Monitor Windows setting in Dalamud combined with Trisha Mode in BossMod, dragging the Boss Module off the primary monitor causes a "burn in" effect on the Module. This is a very specific issue, but being able to have BossMod on my second monitor without having the gray background would be nice.

![image_2022-11-06_013747696](https://user-images.githubusercontent.com/71824000/200157813-102ccc5c-e4e8-4a10-930d-ae0e13e6a7de.png)

**Comment by Rigaln** [comment]
I'm having the same problem.
Turning off the multi-monitor setting cures the burning.
