### ISSUE TITLE
Not getting updates

### ISSUE THREAD

**Issue by vpcn2019** [awgil/ffxiv_bossmod#73]
Hello!

I saw that the current version of the plugin is 72, while mine is still 70. Was there some repo change? I don't really know how plugin updates work, so excuse the dumb question pls :(

**Comment by awgil** [comment]
Yes, there are updates sometimes. Just always update to latest version. Anything before 72 won't work after last patch.

**Comment by Rueby** [comment]
The plugin isn't being updated beyond v70 for me.

**Comment by Dr-Fumbles** [comment]
> 

I tried this and it doesn't work for me... q.q
