### ISSUE TITLE
Not working correctly after hotfix

### ISSUE THREAD

**Issue by sauronshotdogs** [awgil/ffxiv_bossmod#74]
So far, EX3 only shows warnings for Elenchos and nothing else. Not sure about other instances

**Comment by Flavescent** [comment]
In P5S and probably other duties, most AOEs are not displayed

**Comment by Dr-Fumbles** [comment]
In P6S it no longer shows where you are safe from Poly, and other such things it was showing before patch.

**Comment by awgil** [comment]
Are you sure you've all updated the plugin after patch? P5/P6 definitely should be working.

**Comment by Jaky222** [comment]
I just did P5S and P6S a few hours ago. 
It wasn't showing anything for P5S at all, as for P7S the only thing it showed was which side to stand on during Cachexia. As for updating, I assume I was updated, I have it set to auto update and I did hit the update button and there was nothing.

**Comment by Jaky222** [comment]
I just checked. It was v0.0.0.7.
I tried to disable and re-add the plugin still nothing. I got rid of the .json and tried to re-add it and that did it. It's now updated to v0.0.0.73.

Thank you, sir.

**Comment by awgil** [comment]
Ok, this looks like some sort of a dalamud issue, then. I guess everyone with this problem should try to simply remove and readd custom repo if update doesn't work for them.
