### ISSUE TITLE
After the newest maintainance,the plugins is work wrong with the waymarks and the mechanics

### ISSUE THREAD

**Issue by BlanknessWhite** [awgil/ffxiv_bossmod#77]

**Comment by Kingudabat** [comment]
where, im doing all  tier without issues o.o

**Comment by BlanknessWhite** [comment]
> where, im doing all tier without issues o.o
[all 'dump' option in 'general settings' are clicked]
even through open 'Show waymarks on radar',there are no waymarks,and the mechanics are not work(no orange area on radar and wrong machanic of 'Topaz Stone'    all 'dump' option in 'general settings' are clicked

**Comment by BlanknessWhite** [comment]
> where, im doing all tier without issues o.o

thank u so much,it is bcz of the outdated version >  <
