### ISSUE TITLE
Feature request: Raid performance indicator

### ISSUE THREAD

**Issue by Flavescent** [awgil/ffxiv_bossmod#78]
I understand that this plugin cannot measure player DPS directly, but what would be helpful would be an indicator of the rate of boss HP decay to time until enrage - basically, a way to determine whether the raid is killing the boss quickly enough. This could be displayed as a percentage - e.g., if the raid is killing the boss so fast that, assuming a linear relationship between damage and time, it will be at 0% HP when 50% of the time until enrage has elapsed, a "raid performance" indicator of 200% could be displayed.

**Comment by awgil** [comment]
Thought about this, but don't have a concrete vision how to implement this - though your idea of performance percentage is interesting. Measuring 'time to kill' is not as straightforward as it might seem:
1. Not all fights are 100% to 0%: some (e.g. P4S1, P8S1) are until 50%, others (ultimates) have multiple phases with multiple bosses each with separate HP and with separate enrages.
2. Raid dps is not constant, it is significantly higher during burst windows. Besides, some bosses have heavy vuln phases (P8S2, DSR P2, etc.).

**Comment by awgil** [comment]
Currently no plans to implement, due to difficulties described above.
