### ISSUE TITLE
Continued errors after 6.28 hotfix

### ISSUE THREAD

**Issue by sauronshotdogs** [awgil/ffxiv_bossmod#79]
Since the hotfix, I've been having issues with BossMod preventing the plugin list from loading with either this message:
![image](https://user-images.githubusercontent.com/95890035/202901336-79a664b9-f4c6-4132-9957-01913c26a0ae.png)

It happens consistently with Bossmod installed, but never without it. Reinstalling the mod or the repo does nothing, and I basically have to relaunch ffxiv 6 times in order to get it to load. It will sometimes stop working after playing for a couple of hours as well.

When trying to install it again, it will hang on the install message.
![image](https://user-images.githubusercontent.com/95890035/202905501-5b7a4701-dd94-477f-9e8f-6c126d1fad73.png)

**Comment by sauronshotdogs** [comment]
Bossmod is the only plugin this happens with, so I figure it has to do with how it specifically loads some stuff compared to other plugins.

**Comment by joyfulnoise** [comment]
I'm having this same issue. All since 6.28. I'm also wondering if this is being worked on.

**Comment by Paparogue** [comment]
Also happen to have everything stopped working since 6.28 update

**Comment by awgil** [comment]
Yeah no idea about that, can someone with this issue upload some logs so I can investigate?

**Comment by sauronshotdogs** [comment]
Where do you want it uploaded?

**Comment by awgil** [comment]
Anywhere convenient for you... google drive, whatever - and just share the link.

**Comment by sauronshotdogs** [comment]
https://gofile.io/d/VSxYSm

**Comment by sauronshotdogs** [comment]
https://gofile.io/d/d2HsAR

**Comment by llm96** [comment]
I've had the same hang happen intermittently either when installing BossMod for the first time or starting the game with the plugin already installed. After disabling every other plugin, it seems like the cause (as far as I can tell) was Penumbra.

I'm able to get BossMod to load reliably if I remove Penumbra from `XIVLauncher\installedPlugins` before launching the game, then install it again from the Dalamud UI afterwards. For what it's worth, this has happened to me before 6.28.

**Comment by awgil** [comment]
I've looked at the log provided earlier and don't see anything there at all. The only thing that looks weird is this line:
```
2022-11-26 08:57:31.251 +01:00 [INF] [PLUGINM] Loading plugin Boss Mod [Aku API 7]
```
I have no idea what this 'Aku API 7' means, I don't have this locally. If this is some kind of a fork, it might be the problem.

**Comment by sauronshotdogs** [comment]
I think it's because I run dalamud branch 7. The problem persists on stable
though

**Comment by joyfulnoise** [comment]
The [Aku API 7] shows up next to the Boss Mod extensions as Boss Mod [Aku API 7] together in the same. If you enable one, you enable both of them by default. When I re-added Boss Mod, I didn't do anything with [Aku API 7] but it enabled itself. Again, the issue just started with 6.28 and was running fine (even with Penumbra) prior to this.

**Comment by sauronshotdogs** [comment]
It's weird. The last week, there have been no issues, but I've currently restarted the game 16, and it still won't load the plugin, or the plugin list

**Comment by sauronshotdogs** [comment]
It has now completely seized to load, and in the process, preventing my list of plugins from being accessible. I have tried relaunching 19 times so far, but still won't load.

**Comment by joyfulnoise** [comment]
same issue as Sauronshotdog.

**Comment by sauronshotdogs** [comment]
Try deleting it BossMod from installedPLugins and pluginConfigs. Remember to remove the .json file. That seems to have resolved the issue for me most of the time

**Comment by sauronshotdogs** [comment]
Issue is back. Since the creator doesn't seem interested in fixing this issue, Ill just close it.

**Comment by awgil** [comment]
It's not that I'm not interested in fixing - rather, I have no idea what causes this issue and how to fix it - I can't reproduce it locally, and logs don't contain any hints for what might go wrong...

If anyone watches this issue and has more information, feel free to reopen and i'll investigate.

**Comment by llm96** [comment]
Revisiting this as my workaround was getting a bit tedious. I'm not too familiar with how Dalamud plugins work but I'm guessing the issue is that the constructor isn't returning, which causes the Plugin Installer to get stuck infinitely.

I stepped through the constructor and it seems to consistently get stuck on the `MultiboxUnlock.Exec();` line for me.
The debugger was being a bit weird, so I added some debug lines, and yeah, it never hits the 'End' one.

```cs
PluginLog.Debug("MultiboxUnlock.Exec: Start");
MultiboxUnlock.Exec();
PluginLog.Debug("MultiboxUnlock.Exec: End");
```

When the line is commented out the plugin loads reliably.

![MQ73URi](https://user-images.githubusercontent.com/484335/209884125-a96dbe3c-f532-47c1-a6c1-c49602be109b.png)

Hope this is useful.

**Comment by awgil** [comment]
Oh thanks a lot for that, will fix asap!

**Comment by awgil** [comment]
Disabled the corresponding code in release versions, I don't think anyone really cares about it. Please tell me whether the problem is still reproducible with latest version.

**Comment by awgil** [comment]
@llm96 I've added some extra checks to the handle checking code - since you've debugged this issue locally, could you try building head of the master and verifying that it doesn't reproduce for you?

**Comment by llm96** [comment]
> @llm96 I've added some extra checks to the handle checking code - since you've debugged this issue locally, could you try building head of the master and verifying that it doesn't reproduce for you?

All looks good now. Both the latest release and build from master load now without any issues. 👍

**Comment by awgil** [comment]
Cool, then I'm assuming this annoying issue is finally resolved.
