### ISSUE TITLE
Cardinal directions readability and visibility & lower size/scale issues

### ISSUE THREAD

**Issue by NyxOfficials** [awgil/ffxiv_bossmod#80]
The cardinal directions scaling impacts the readability and visibility of the letters. Maybe having a different slider to scale them would be better also. Having the option to change the colour of the letters would improve/solve this issue maybe adding a background for the letters might also help. Another suggestion is that the north (N) cardinal should always be red or in a separate colour control as it can be used in many mechanics and is important to be visible.

**Comment by awgil** [comment]
Outdated, there's an option for this already.
