### ISSUE TITLE
Mini map for boss still not showing up

### ISSUE THREAD

**Issue by bostonpsycho** [awgil/ffxiv_bossmod#81]
The boss mod mini map for any/all bosses isn't popping up during the battle. 

Also maybe a guide on how the different configs would work would be beneficial.

**Comment by Kingudabat** [comment]
https://github.com/awgil/ffxiv_bossmod/tree/master/BossMod/Modules  here u can look the fights where is working, its not for everything.

**Comment by sauronshotdogs** [comment]
It could also be that it just fails at loading. Check your plugin list or do /vbm

**Comment by Ants1988** [comment]
/vbm -> click on "Boss Module Settings" and make sure "Enable Boss Modules" is ticked.

The plugin's working fine for me.

**Comment by strik3r93** [comment]
Same to me that plugin doesnt want to be installed at all q_q.

**Comment by JohnRiegle** [comment]
I see that the critical engagements are being added. I can’t get them to pop up. Are they not ready yet or do I have to do something to get them to work?

**Comment by awgil** [comment]
Outdated.
