### ISSUE TITLE
Autorotation guide

### ISSUE THREAD

**Issue by vpcn2019** [awgil/ffxiv_bossmod#85]
Could you please make some sort of a short guide on how to use the autorotation feature? I'm leveling a WHM and I thought to try it out, but at lvl 75 all I'm getting is "spell (0) automatic". Do I need to be of a specific level? Do I need to be using only Glare for ST rotation?

**Comment by awgil** [comment]
Yeah, autorotation doesn't really work that well, it's a very experimental feature, so you might as well ignore it for now.
