### ISSUE TITLE
[Request] Add a click-through option to the window/add opacity slider

### ISSUE THREAD

**Issue by PestoPresto** [awgil/ffxiv_bossmod#88]
Adding an option to be unable to interact with the window can prevent accidentally moving the window during a fight, and also prevent the window from eating clicks on screen.

Also, Trisha mode is great for making the arena easier to look at, but sometimes makes the hints hard to see depending on the fight. Adding opacity sliders for both the window and the arena floor would let users personalize the values for their eyes or the fight.

**Comment by awgil** [comment]
Outdated, there's option for this already.
