### ISSUE TITLE
Critical engagements

### ISSUE THREAD

**Issue by Berticus22** [awgil/ffxiv_bossmod#90]
I see that the critical engagements have been added. I can’t get them to come up when I’m in the engagements. Are they not ready yet or is there something I have to do to get them to work?

Side note: The ones that have came up are a life saver. Keep up the great work.

**Comment by awgil** [comment]
That's work in progress.

**Comment by Berticus22** [comment]
Thanks for the update, I figured it was still in work, I just wanted to make sure.

**Comment by awgil** [comment]
Outdated. Modules are added as they are created.
