### ISSUE TITLE
Blocking Plugin Installer

### ISSUE THREAD

**Issue by believeinyuna** [awgil/ffxiv_bossmod#91]
i am unable to open the plugin installer /xlplugins with bossmod installed, with a message saying one of my plugins is blocking the installer. so i took it out and tried to reinstall it, and it infinitely gets stick on "installing plugin...". if i close the plugin installer it gets infinitely stuck on "loading repositories and plugins..." until i close the game, and i have to take out bossmod from my installed plugins folder again. 

edit: it opens by itself, so i must have a conflicting plugin somewhere. will report back with whatever it is when i find out.

**Comment by awgil** [comment]
Please upload the log somewhere, I'll investigate.

**Comment by believeinyuna** [comment]
i'm still going through plugins to figure out which one makes bossmod block, lots of them are blocking so far
[dalamud.log](https://github.com/awgil/ffxiv_bossmod/files/10307815/dalamud.log)

**Comment by believeinyuna** [comment]
all of these blocked my plugins installer when bossmod was included in the install. when i remove bossmod none of these block. i've included the log that i got from loading them all with bossmod.

![image](https://user-images.githubusercontent.com/27219533/209660616-394e0feb-a2e9-4ca7-8d13-
[dalamud.log](https://github.com/awgil/ffxiv_bossmod/files/10307910/dalamud.log)
b52621e3f57a.png)

**Comment by awgil** [comment]
No idea, can't see anything relevant in the log.

This looks to be the same issue as #79.

**Comment by awgil** [comment]
Please check whether it is reproducible in newest version.

**Comment by Ants1988** [comment]
> all of these blocked my plugins installer when bossmod was included in the install. when i remove bossmod none of these block. i've included the log that i got from loading them all with bossmod.
> 
> ![image](https://user-images.githubusercontent.com/27219533/209660616-394e0feb-a2e9-4ca7-8d13-b52621e3f57a.png) [dalamud.log](https://github.com/awgil/ffxiv_bossmod/files/10307910/dalamud.log)

Pingplugin has never blocked bossmod for me, so idk.

**Comment by DatGoose** [comment]
I've had some problems like this in the past and my resolution to the issue was to purge my entire plugin folder and config folder and start over, this cleared up the issue. Sure it is a small inconvenience with having to set somethings back up but its better than dealing with this annoying issue. Also only grab the plugin from the source repo, any mega repo can cause major issues.

**Comment by Kumicoo** [comment]
For me, bossmod is not showing up, even when manually installing, something is turbo broken, or maybe dalamud devs blocked bossmod?

**Comment by GREYsaurus** [comment]
Bossmod wasn't showing up for me today using the custom repo in dalamud. But i cloned it and built a copy in my VS and works fine that way as a devPlugin. So it'll be my work around for now, just giving a heads up with the repo link issue
