### ISSUE TITLE
[P7S] Extra Yellow Flare markers

### ISSUE THREAD

**Issue by Rueby** [awgil/ffxiv_bossmod#92]
For some reason in P7S the exaflares near the edge are a distracting bright yellow. This didn't happen before last I checked? (two weeks ago or so) 

Was this change intentional or not? It happens during the time of healer stacks + KB around hmm 5mins into the fight.

**Comment by awgil** [comment]
Yeah that's intentional - I want to highlight next/imminent aoe for exaflare-like mechanics.

If you don't like the colors, feel free to suggest some different colors :) I really suck at making ux decisions.

**Comment by Rueby** [comment]
Ohh I see, well I'll try to take a pic of it next time to show you. Hmmm there's exaflares in Nald'Thal's fight and they stack up nicely without being too much.

My suggestion is to lower the opacity of the most intense one so it's not this glaring yellow? 

(I'll provide a pic when I'm able)

**Comment by awgil** [comment]
Outdated. This is the default color scheme for exaflares, at some point color scheme will be customizable.
