### ISSUE TITLE
Not showing up in 6.3

### ISSUE THREAD

**Issue by Kumicoo** [awgil/ffxiv_bossmod#93]
Its not showing up in the plugin list, even when installed manually. When installed manually, it additionally removes itself from the folder. "installedplugins". whats going on?

**Comment by Kingudabat** [comment]
x2 i  dont even saw the plugin o.o

**Comment by awgil** [comment]
It's not updated for 6.3 yet. Waiting for public dalamud release, lots of stuff has changed.

Since you're apparently using non-public release, you can build from sources manually meanwhile.

**Comment by awgil** [comment]
Published the update.
