### ISSUE TITLE
Is this detectable in any way? 

### ISSUE THREAD

**Issue by Laurawrn** [awgil/ffxiv_bossmod#94]
Hey, I know it might be a bit of a silly question but I was wondering if this plugin sends anything to the SE servers that might trigger a flag on their end? I'm always a little hesitant with using new plugins.

Thanks!

**Comment by banjorae** [comment]
Yes, they will ban you

**Comment by awgil** [comment]
It depends on the features that you use.

Basic boss modules should not be detectable, they only read stuff. Features marked as 'experimental' in config might be theoretically detectable - these are all disabled by default.

In any case, using the plugin should never result in game sending something that it couldn't with some specific player actions (of course, barring some unknown bugs).

**Comment by Ants1988** [comment]
Just don't tell anyone you're using the plugin and your chances of being caught is 0.
