### ISSUE TITLE
Trying to install 

### ISSUE THREAD

**Issue by Vullius** [awgil/ffxiv_bossmod#98]
Had the plugin in dalamund before the patch tried multiple times to re add the plugin but keeps saying Donwload Failed???

**Comment by Ants1988** [comment]
Uninstall the plugin.

Remove the link from repos, readd the link and reinstall plugin.

I can't replicate your problem myself.

**Comment by awgil** [comment]
Yeah, if removing/reinstalling a plugin or removing/readding a repo works, it's probably something on dalamud side.
